### ISSUE TITLE
scipy test on AIX hangs with openblass.

### ISSUE THREAD

**Issue by sameer-dubal** [scipy/scipy#10093]
Hi, 
I am sameer and I am part of IBM AIX team.  I am facing hang issue with scipy on AIX. 
Scipy test hangs on aix  with open blas. 
test hangs at 37 percent on below scrip.
" opt/freeware/lib64/python3.7/site-packages/scipy/sparse/linalg/isolve/tests/test_gcrotmk.py" 
above test script passes successfully when i tries to execute it individually. 

========
(0) root @ fcdd7: /
# python3 opt/freeware/lib64/python3.7/site-packages/scipy/sparse/linalg/isolve/tests/test_gcrotmk.py

(0) root @ fcdd7: /
#
========
@rgommers  Hi ,I have seen you contributing for AIX for some of the issue , i ll really appreciate if you can help in the issue.  

### 
**Open Blas compilation steps on AIX power.** 
==
git clone https://github.com/xianyi/OpenBLAS 

git checkout v0.3.5 

cd OpenBLAS 
make BINARY=64 CC="gcc -maix64" FC="gfortran -maix64" CXX="g++ -maix64" TARGET=POWER7 

==

# python3
Python 3.7.1 (default, Jan 11 2019, 17:16:05)
[GCC 6.3.0] on aix6
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.version.version
'1.16.2'
>>>
>>> scipy.version.version
'1.2.1'
>>>

=============================================================
# python3
Python 3.7.1 (default, Jan 11 2019, 17:16:05)
[GCC 6.3.0] on aix6
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy as sp
>>> sp.test()
=================================================================================== test session starts ====================================================================================
platform aix6 -- Python 3.7.1, pytest-4.4.1, py-1.8.0, pluggy-0.9.0
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/.hypothesis/examples')
rootdir: /
plugins: hypothesis-4.17.2
collected 16700 items / 1223 deselected / 15477 selected

.
.
.
.
.

opt/freeware/lib64/python3.7/site-packages/scipy/sparse/csgraph/tests/test_connected_components.py ......                                                                            [ 36%]
opt/freeware/lib64/python3.7/site-packages/scipy/sparse/csgraph/tests/test_conversions.py ...                                                                                        [ 36%]
opt/freeware/lib64/python3.7/site-packages/scipy/sparse/csgraph/tests/test_graph_laplacian.py ....                                                                                   [ 36%]
opt/freeware/lib64/python3.7/site-packages/scipy/sparse/csgraph/tests/test_reordering.py ....                                                                                        [ 36%]
opt/freeware/lib64/python3.7/site-packages/scipy/sparse/csgraph/tests/test_shortest_path.py ..........                                                                               [ 36%]
opt/freeware/lib64/python3.7/site-packages/scipy/sparse/csgraph/tests/test_spanning_tree.py .                                                                                        [ 36%]
opt/freeware/lib64/python3.7/site-packages/scipy/sparse/csgraph/tests/test_traversal.py ....                                                                                         [ 36%]
opt/freeware/lib64/python3.7/site-packages/scipy/sparse/linalg/dsolve/tests/test_linsolve.py .s.s.s.s.ss.......s..................                                                   [ 36%]
opt/freeware/lib64/python3.7/site-packages/scipy/sparse/linalg/eigen/arpack/tests/test_arpack.py ..............................                                                      [ 36%]
opt/freeware/lib64/python3.7/site-packages/scipy/sparse/linalg/eigen/lobpcg/tests/test_lobpcg.py ............                                                                        [ 37%]
opt/freeware/lib64/python3.7/site-packages/scipy/sparse/linalg/isolve/tests/test_gcrotmk.py ......

=======================================================

**Comment by rgommers** [comment]
Hi @sameer-dubal, thanks for the report. It could be the same cause as gh-9595, which is fixed in master but not in 1.2.1. Did you try with master? Alternatively, to save you rebuilding, the PRs for fixing that issue are only a few lines, so you can just copy them over into `opt/freeware/lib64/python3.7/site-packages/scipy/sparse/linalg/isolve/tests/` manually.

**Comment by sameer-dubal** [comment]
Hi @rgommers thanks for the reply. 
I have tried with rebuilding scipy master build also , but still facing the same issue. 

Is their any way to execute "scipy/sparse/linalg/isolve/tests/test_gcrotmk.py " script seperatly in python to debug. I have tried to debug it with pdb but no luck . 
tried steps 
1) edit the script with pdb and tracepoints in each function of the script. 
2) python3 runtests.py  
pdb and trace points are not hit  and still execution hangs at 37 %  at "scipy/sparse/linalg/isolve/tests/test_gcrotmk.py". 

is their any different way to debug "scipy/sparse/linalg/isolve/tests/test_gcrotmk.py "?

**Comment by rgommers** [comment]
> I have tried with rebuilding scipy master build also , but still facing the same issue.

That's too bad, it's a real issue then. Possibly in OpenBLAS, otherwise in our code.

> Is their any way to execute "scipy/sparse/linalg/isolve/tests/test_gcrotmk.py " script seperatly in python to debug. 

If you're using `runtests.py` then to run all tests for a submodule or some subset
```
python runtests.py -s scipy.sparse.linalg.isolve   # any submodule
python runtests.py -t TestGCROTMK   # any expression (not 100% sure a filename works)
```

For an installed SciPy version, use `pytest`:
```
pytest --pyargs scipy -k test_gcrotmk.py
```

**Comment by sameer-dubal** [comment]
@rgommers  thanks for the response , I will try to debug further with -s option.
