### ISSUE TITLE
RuntimeWarning: invalid value encountered in stats.genextreme

### ISSUE THREAD

**Issue by fabio-gut** [scipy/scipy#10446]
This issue is about trying to fit a Generalized Extreme Value Distribution to a sample dataset. However it is giving me a runtime warning and absurd fitting parameters. If I only use a subset of the datapoints (first 2000/2848 for example) it works just fine. All datapoints are floats and none are 0 or nan.

### Reproducing code example:
Since this is tied to the data used, i have a repo with the sample data and a tiny testcase to showcase the issue [here](https://github.com/fabio-gut/scipy_bug). Simply run the script to produce the warning.

### Error message:
```python
/usr/lib/python3.7/site-packages/scipy-1.3.0-py3.7-linux-x86_64.egg/scipy/stats/_continuous_distns.py:2402: RuntimeWarning: invalid value encountered in subtract
  -pex2+logpex2-logex2)
```

### Scipy/Numpy/Python version information:
```python
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.3.0 1.16.4 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
```

**Comment by WarrenWeckesser** [comment]
> Since this is tied to the data used, i have a repo with the sample data and a tiny testcase to showcase the issue here. Simply run the script to produce the warning.

Thanks, that's very helpful!

This needs further investigation, but I suspect some numerical issue is sending the optimizer off into the weeds.

I get a reasonable result if I include a starting value for the shape parameter in the `fit` call:

```
In [12]: x = np.array(read_data())                                                                     

In [13]: params = gev.fit(x, 3.0)  # The second argument is the initial guess for the shape parameter                                                            

In [14]: params
Out[14]: (0.4315302331910096, -6.513395970329862, 2.939562307182096)

In [15]: ignore = plt.hist(x, bins=50, alpha=0.5, density=True)                                        

In [16]: xx = np.linspace(x.min()-1, 0, 500)                                                           

In [17]: plt.plot(xx, gev.pdf(xx, *params), 'k', alpha=0.5) 
```
![Figure_1](https://user-images.githubusercontent.com/321463/61137393-6a2d1d00-a493-11e9-8d00-b55e4003eb7d.png)

**Comment by fabio-gut** [comment]
Good catch on that one!
Will use that untill this bug is fixed thanks!

**Comment by plvoit** [comment]
Hey everyone,
for me it didn't help to include a starting value in gev.fit(). I'm still getting the same error as fabio. Did anyone gain further insights about how to solve this issue by now?
Thanks,
Paul

**Comment by mdhaber** [comment]
This is being tracked in gh-11782, so I'll go ahead and close this one. In the meantime, another option is [`scipy.stats.fit`](http://scipy.github.io/devdocs/reference/generated/scipy.stats.fit.html#scipy.stats.fit), which will be available in SciPy 1.9.0. Two features that may help here:
* it allows (currently requires, actually) the user to specify bounds for parameters, so you can use this to help the optimizer stay in the right ballpart, and
* by default it uses a global optimizer, `scipy.optimize.differential_evolution`, to start the optimization, then polishes the fit with a gradient-based optimizer.
