### ISSUE TITLE
nnz of the result is too large

### ISSUE THREAD

**Issue by Ganeshpadmanaban** [scipy/scipy#12495]
The issue occurred in Scipy==1.4.1.

`RuntimeErrorscipy.sparse.compressed in _mul_sparse_matrix error //
nnz of the result is too large`

Matrix "a" and "b":
```
{a: <262914x997446 sparse matrix of type '<class 'numpy.float32'>'
with 36293228 stored elements in Compressed Sparse Row format>, 
b: <997446x262914 sparse matrix of type '<class 'numpy.float32'>'
with 36293228 stored elements in Compressed Sparse Column format>, 
dense_output: False}
```

**Comment by mdhaber** [comment]
I imagine a minimum working example to reproduce this bug is quite large.
It sounds matrix multiplication between `a` and `b` is failing? I haven't looked at the code, but would you try manually converting the `indices` and `indptr` arrays of the matrices to `np.int64` before doing multiplication?
```
def convert_to_64bit_indices(A):
    A.indptr = np.array(A.indptr, copy=False, dtype=np.int64)
    A.indices = np.array(A.indices, copy=False, dtype=np.int64)
    return A
a = convert_to_64bit_indices(a)
b = convert_to_64bit_indices(b)
```

Then do the operation?

**Comment by ewmoore** [comment]
I suspect you're correct that manually converting to `np.int64` will do it.  I'm pretty sure that the error actually originates [here](https://github.com/scipy/scipy/blob/maintenance/1.4.x/scipy/sparse/sparsetools/csr.h#L591).  I'm not sure why `_mul_sparse_matrix` is picking `int32` for the index dtype though.   @Ganeshpadmanaban, are you sure that you have Scipy 1.4.2 and not 1.5.x?  

It does look like there is an issue with `csr @ csr` on 1.5.x / master. The code introduced in #11478 has an error.  In the master branch, `csr_matmat_maxnnz` will throw this error when called with `int32` index arrays, even though we are computing the new `nnz` to (in part) see if we need `int64` as an index dtype.  The `next_nnz != (I)next_nnz` part of the comparison isn't needed now.  `csr_matmat_maxnnz` is or should be always computing the new `nnz`  as `int64`.  I haven't made this fail, since I don't have access to a machine with enough ram.  Hopefully someone else can look and see the same thing that I see.

**Comment by perimosocordiae** [comment]
@Ganeshpadmanaban can you try using the current master and see if @ewmoore's change fixed this?

**Comment by EssentiallyNoah** [comment]
@ewmoore Just to add some closure to the issue, I got the same error with Scipy==1.5.2. Updated to 1.6.0 and it looks like the issue was fixed.

**Comment by ewmoore** [comment]
Glad to hear it.

**Comment by hahmad2008** [comment]
I use spicy 1.6.0 and still have the same issue, Is this problem due to using python 3.6?

```
__mul__
    return self._mul_sparse_matrix(other)
  File "/usr/local/lib/python3.6/dist-packages/scipy/sparse/compressed.py", line 509, in _mul_sparse_matrix
    np.asarray(other.indices, dtype=idx_dtype))
RuntimeError: nnz of the result is too large
```
