### ISSUE TITLE
Unable to install scipy on Mac Osx Big Sur

### ISSUE THREAD

**Issue by ernestoarbitrio** [scipy/scipy#13102]
After Big Sur update I'm not able to install scipy in any of my virtualenvs.

```
pip install scipy
```

generate this error

```bash
    numpy.distutils.system_info.NotFoundError: No lapack/blas resources found. Note: Accelerate is no longer supported.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/ernestoarbitrio/.virtualenvs/histolab/bin/python /Users/ernestoarbitrio/.virtualenvs/histolab/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/3j/s7l7gl410xx64sk3zg9_ngh40000gn/T/tmppxmdgj6o Check the logs for full command output.
```

**Comment by andyfaff** [comment]
Is pip trying to build from source? What version of numpy do you have installed? Are you on Apple Silicon, or Intel still?

**Comment by ernestoarbitrio** [comment]
numpy 1.18.0 (the latest version has some issues on my laptop)
yes trying to build from source
and still Intel CPU

i tried ... system wide (using pyenv) the only way it works is under a conda environment

**Comment by andyfaff** [comment]
Check out the devdocs, http://scipy.github.io/devdocs/building/macosx.html, they may help.

**Comment by ernestoarbitrio** [comment]
k thanks

**Comment by samkuehn** [comment]
I am having the same issue on both Apple Silicon, and Intel.  This was working correctly on BigSur a week or two ago but seems to have stopped.  I have noticed that a couple of other python libraries with C extensions have quit working too.  Checked out devdocs and installing openblas (`brew install openblas`) did not help.

**Comment by andyfaff** [comment]
All bets are off for apple silicon, I don't think we've tried building on there yet, but it'll come.

Not sure about Big Sur and Intel though, I would've thought building would work there. However, it's not clear why a prebuilt wheel isn't being installed to start with. Does numpy install and run its test suite ok?

**Comment by samkuehn** [comment]
I am able to install numpy in a virtualenv `pip install numpy`
(Successfully installed numpy-1.19.4).

I downloaded the numpy source and was able to run the test suit as well.
== 12071 passed, 929 skipped, 1205 deselected, 21 xfailed in 83.73s (0:01:23) ==

It seems like all of the sudden the prebuilt wheels quit being installed and everything stated getting compiled from source.  Fairly sure when these packages were working earlier it was just installing the prebuilt wheel but I cannot be positive.  It was working correctly so I didn't pay much attention.  I am rebuilding a few virtual environments now and I am running into issues with c extensions failing compilation on some packages.

**Comment by samkuehn** [comment]
I was able to manually install the wheel by going here https://pypi.org/project/scipy/#files and downloading the cPython 3.7 wheel and running.
`pip install scipy-1.5.4-cp37-cp37m-macosx_10_9_x86_64.whl`

The first time it errored out with the message
scipy-1.5.4-cp37-cp37m-macosx_10_9_x86_64.whl is not a supported wheel on this platform.

I renamed the wheel to scipy-1.5.4-cp37-none-any.whl  and ran
`pip install scipy-1.5.4-cp37-none-any.whl`
and it worked.

I am guessing pip is looking for scipy-1.5.4-cp37-cp37m-macosx_11_0_x86_64.whl on BigSur or something.

**Comment by samkuehn** [comment]
Although that did install, it didn't ultimately work - I got this error when trying to run my application.


  File "/Users/<username>/.virtualenvs/<appname>/lib/python3.7/site-packages/numpy/__init__.py", line 286, in <module>
    raise RuntimeError(msg)
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
RankWarning: Polyfit may be poorly conditioned

**Comment by tylerjereddy** [comment]
@seberg noted this to me a few days ago (from NumPy core team):

> Just FYI, in case you guys also have problems with the mac wheels and new XCODE version. We decided to keep building the 10_9 wheels, but start uploading them as 11_0  (by simply renaming the file)

**Comment by seberg** [comment]
Yes, basically you can download the current wheel and rename it to `11_0` and it will work. @mattip asked people on a numpy issue to try it, and everyone reported that it was a solution for them (you can pip install from an explicit downloaded file). The same should work as a hotfix for you @samkuehn both for numpy and scipy.

**Comment by andyfaff** [comment]
@seberg, is the wheel renaming something that should be dealt with upstream, or here.

**Comment by charris** [comment]
I can download the 19.4 Mac wheels, rename them, and then upload them. Would that be helpful?

**Comment by andyfaff** [comment]
If there are two users having issues then it seems that would be useful. Is the underlying issue an upstream python wheel tag problem, or is scipy building things incorrectly?

**Comment by mattip** [comment]
It is an issue that should be solved by this PR pypa/packaging#319 (packaging is used by pip to validate tags). But until then uploading renamed wheels would help.

**Comment by charris** [comment]
> But until then uploading renamed wheels would help.

Whelp, that doesn't work, pypi refuses the renamed files as duplicates.
```
Uploading numpy-1.19.4-cp37-cp37m-macosx_11_0_x86_64.whl
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 14.6M/14.6M [00:53<00:00, 288kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
File already exists. See https://pypi.org/help/#file-name-reuse for more information.
```

**Comment by seberg** [comment]
We could make a completely meaningless change to change the hashsum I guess?

**Comment by matthew-brett** [comment]
Use a build tag in the wheel filename maybe?

**Comment by mattip** [comment]
I am not sure whether a [build tag](https://www.python.org/dev/peps/pep-0425/#use) `numpy-1.19.4-1-cp37-cp37m-macosx_11_0_x86_64.whl` would still fall afoul of the "A file with the exact same content exists" rule for [file name re-use](https://pypi.org/help/#file-name-reuse).

**Comment by andyfaff** [comment]
Can wheels be retroengineered to add an empty byte at the start or end that would change the hash? Or is that a bad thing to do with respect to integrity?

**Comment by jwischka** [comment]
As a preview, it looks like SciPy is going to have some problems building in current form on Apple Silicon. 

As background, I tried building NumPy from 1.19.4 (current stable) and ran into similar errors as I'm seeing on the current 1.6.0 dev branch on SciPy (linking against a native darwin-arm64 OpenBLAS build). I'm not sure what was done on the NumPy side, but 1.20 dev currently builds and installs with no problem. So the solutions for that part of things may be over there in a recent-ish commit.

As some heads up, it looks like something is passing both arm64 and x86_64 architectures to clang for the build process:

```
    openblas_lapack_info:
    C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64
```

... which may then be causing problems with including some symbols that exist in x86_64 but not in arm64.

```
    clang /var/folders/rr/b7gr0p9d5lzd2g2r5rbkfy180000gn/T/tmp16goayjk/var/folders/rr/b7gr0p9d5lzd2g2r5rbkfy180000gn/T/tmp16goayjk/source.o -L/opt/OpenBLAS/lib -lopenblas -o /var/folders/rr/b7gr0p9d5lzd2g2r5rbkfy180000gn/T/tmp16goayjk/a.out
    Undefined symbols for architecture arm64:
      "_zungqr_", referenced from:
          _main in source.o
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
      NOT AVAILABLE
```

Or, at least, that's my current working theory. As I said, I was getting similar errors building NumPy 1.19.4, but 1.20-dev builds correctly, so at least part of the solution may be there.

I'm not familiar with the guts of either NumPy or SciPy, so I may not be able to contribute a ton on the coding side, but I'm happy to help out and test builds if I can.

**Comment by JorgenPhi** [comment]
I have an Intel Mac, with a fresh copy of Big Sur.

I was able to build NumPy from source after installing openblas with brew, and then adding a `site.cfg` to the numpy root to show it where openBLAS is located. [Here's a Gist demonstrating that ](https://gist.github.com/yatsu/47bdde35e8abbe7d14bbe730342aa9e0)

However, when I try the same with SciPy I get something much more bizarre:
```
  2 warnings generated.
  Running from scipy source directory.
  /private/var/folders/5b/t_pg6zg94ys7ywxhfjppzhnw0000gn/T/pip-build-env-tvijd_yy/overlay/lib/python3.8/site-packages/numpy/distutils/system_info.py:782: UserWarning: Specified path /private/var/folders/5b/t_pg6zg94ys7ywxhfjppzhnw0000gn/T/pip-build-env-tvijd_yy/overlay/include/python3.8 is invalid.
    return self.get_paths(self.section, key)
  /private/var/folders/5b/t_pg6zg94ys7ywxhfjppzhnw0000gn/T/pip-build-env-tvijd_yy/overlay/lib/python3.8/site-packages/numpy/distutils/system_info.py:782: UserWarning: Specified path /usr/local/include/python3.8 is invalid.
    return self.get_paths(self.section, key)
  /private/var/folders/5b/t_pg6zg94ys7ywxhfjppzhnw0000gn/T/pip-build-env-tvijd_yy/overlay/lib/python3.8/site-packages/numpy/distutils/system_info.py:782: UserWarning: Specified path /Users/jorgen/code/a/caravel/venv/include/python3.8 is invalid.
    return self.get_paths(self.section, key)
  error: Command "clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -DUSE_VENDOR_BLAS=1 -Iscipy/sparse/linalg/dsolve/SuperLU/SRC -I/private/var/folders/5b/t_pg6zg94ys7ywxhfjppzhnw0000gn/T/pip-build-env-tvijd_yy/overlay/lib/python3.8/site-packages/numpy/core/include -c scipy/sparse/linalg/dsolve/SuperLU/SRC/clacon2.c -o build/temp.macosx-10.14.6-x86_64-3.8/scipy/sparse/linalg/dsolve/SuperLU/SRC/clacon2.o -MMD -MF build/temp.macosx-10.14.6-x86_64-3.8/scipy/sparse/linalg/dsolve/SuperLU/SRC/clacon2.o.d" failed with exit status 1
```

Not sure what it's looking for, but there is not any python3.8 files or directories in the directories it's searching for.

**Comment by JorgenPhi** [comment]
For anyone else that needs SciPy to just install for now, here's what I did to make it work:

1. Find your tag
```
$ pip install packaging
$ python -c"from packaging import tags; print('\n'.join([str(t) for t in tags.sys_tags()]))" |head -5

cp38-cp38-macosx_11_0_x86_64
```

2. Download 10_9 wheel from Pypi https://pypi.org/project/scipy/#files

3. Rename downloaded file to match your tag
`$ mv scipy-1.5.4-cp38-cp38-macosx_10_9_x86_64.whl scipy-1.5.4-cp38-cp38-macosx_11_0_x86_64.whl`

4. Install wheel
`$ pip install scipy-1.5.4-cp38-cp38-macosx_11_0_x86_64.whl`

**Comment by tylerjereddy** [comment]
@rgommers Do we want to try to manually upload 3 additional SciPy MacOS wheels per the renaming scheme above for the 1.6.0 release or?

I think it is not immediately clear to me if we can avoid issues with files having binary-exact matching content, but different names and hashes for any checks that might happen.

**Comment by mattip** [comment]
I think this is solved with the new release of pip, which added support for macOSx 11 to install wheels with a 10_9 tag.

**Comment by kkozmic** [comment]
> I think this is solved with the new release of pip, which added support for macOSx 11 to install wheels with a 10_9 tag.

Still failing for me (using `pyenv`) with latest pip (`pip 20.3 from /Users/myuser/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pip (python 3.8)`

**Comment by mattip** [comment]
@kkozmic what did you try and what was the error?

**Comment by rgommers** [comment]
> @rgommers Do we want to try to manually upload 3 additional SciPy MacOS wheels per the renaming scheme above for the 1.6.0 release or?

I'd prefer to not do that, since it may hide other issues. The packaging toolchain is being updated, so let's just do it the right way.

**Comment by kkozmic** [comment]
> @kkozmic what did you try and what was the error?

I'm using Poetry (1.1.4), running `poetry install` on my project, so can't easily go around downloading/renaming files.
This is under Python 3.8.6 in `pyenv` running on an Intel Macbook Pro with Big Sur 11.0.1

<details>
  <summary>Full log. Click to expand (long)</summary>

```

  • Installing scipy (1.5.2): Failed

  EnvCommandError

  Command ['/Users/my-user/projects/my-project/.venv/bin/pip', 'install', '--no-deps', 'file:///Users/my-user/Library/Caches/pypoetry/artifacts/2f/b1/6e/302949c7b1aeb2d81b181900de55a0504d2060e751aa6c2e3985b4b4fb/scipy-1.5.2.tar.gz'] errored with the following return code 1, and output:
  Processing /Users/my-user/Library/Caches/pypoetry/artifacts/2f/b1/6e/302949c7b1aeb2d81b181900de55a0504d2060e751aa6c2e3985b4b4fb/scipy-1.5.2.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /Users/my-user/projects/my-project/.venv/bin/python /Users/my-user/projects/my-project/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/ls/j8gt2mcd02s9z5yqbgt297h80000gn/T/tmp6l431_j2
           cwd: /private/var/folders/ls/j8gt2mcd02s9z5yqbgt297h80000gn/T/pip-req-build-ggiz013l
      Complete output (139 lines):
      lapack_opt_info:
      lapack_mkl_info:
      customize UnixCCompiler
        libraries mkl_rt not found in ['/Users/my-user/projects/my-project/.venv/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      openblas_lapack_info:
      customize UnixCCompiler
      customize UnixCCompiler
        libraries openblas not found in ['/Users/my-user/projects/my-project/.venv/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      openblas_clapack_info:
      customize UnixCCompiler
      customize UnixCCompiler
        libraries openblas,lapack not found in ['/Users/my-user/projects/my-project/.venv/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      flame_info:
      customize UnixCCompiler
        libraries flame not found in ['/Users/my-user/projects/my-project/.venv/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      atlas_3_10_threads_info:
      Setting PTATLAS=ATLAS
      customize UnixCCompiler
        libraries lapack_atlas not found in /Users/my-user/projects/my-project/.venv/lib
      customize UnixCCompiler
        libraries tatlas,tatlas not found in /Users/my-user/projects/my-project/.venv/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries tatlas,tatlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib
      customize UnixCCompiler
        libraries tatlas,tatlas not found in /usr/lib
      <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
        NOT AVAILABLE

      atlas_3_10_info:
      customize UnixCCompiler
        libraries lapack_atlas not found in /Users/my-user/projects/my-project/.venv/lib
      customize UnixCCompiler
        libraries satlas,satlas not found in /Users/my-user/projects/my-project/.venv/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries satlas,satlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib
      customize UnixCCompiler
        libraries satlas,satlas not found in /usr/lib
      <class 'numpy.distutils.system_info.atlas_3_10_info'>
        NOT AVAILABLE

      atlas_threads_info:
      Setting PTATLAS=ATLAS
      customize UnixCCompiler
        libraries lapack_atlas not found in /Users/my-user/projects/my-project/.venv/lib
      customize UnixCCompiler
        libraries ptf77blas,ptcblas,atlas not found in /Users/my-user/projects/my-project/.venv/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib
      customize UnixCCompiler
        libraries ptf77blas,ptcblas,atlas not found in /usr/lib
      <class 'numpy.distutils.system_info.atlas_threads_info'>
        NOT AVAILABLE

      atlas_info:
      customize UnixCCompiler
        libraries lapack_atlas not found in /Users/my-user/projects/my-project/.venv/lib
      customize UnixCCompiler
        libraries f77blas,cblas,atlas not found in /Users/my-user/projects/my-project/.venv/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries f77blas,cblas,atlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib
      customize UnixCCompiler
        libraries f77blas,cblas,atlas not found in /usr/lib
      <class 'numpy.distutils.system_info.atlas_info'>
        NOT AVAILABLE

      accelerate_info:
        NOT AVAILABLE

      lapack_info:
      customize UnixCCompiler
        libraries lapack not found in ['/Users/my-user/projects/my-project/.venv/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      lapack_src_info:
        NOT AVAILABLE

        NOT AVAILABLE

      setup.py:460: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /private/var/folders/ls/j8gt2mcd02s9z5yqbgt297h80000gn/T/pip-modern-metadata-ug779qrr'), proceeding with generating Cython sources and expanding templates
        warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
      Running from SciPy source directory.
      /private/var/folders/ls/j8gt2mcd02s9z5yqbgt297h80000gn/T/pip-build-env-p8fk30ek/overlay/lib/python3.8/site-packages/numpy/distutils/system_info.py:1712: UserWarning:
          Lapack (http://www.netlib.org/lapack/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [lapack]) or by setting
          the LAPACK environment variable.
        if getattr(self, '_calc_info_{}'.format(lapack))():
      /private/var/folders/ls/j8gt2mcd02s9z5yqbgt297h80000gn/T/pip-build-env-p8fk30ek/overlay/lib/python3.8/site-packages/numpy/distutils/system_info.py:1712: UserWarning:
          Lapack (http://www.netlib.org/lapack/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [lapack_src]) or by setting
          the LAPACK_SRC environment variable.
        if getattr(self, '_calc_info_{}'.format(lapack))():
      Traceback (most recent call last):
        File "/Users/my-user/projects/my-project/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
          main()
        File "/Users/my-user/projects/my-project/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/my-user/projects/my-project/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/ls/j8gt2mcd02s9z5yqbgt297h80000gn/T/pip-build-env-p8fk30ek/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 161, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/ls/j8gt2mcd02s9z5yqbgt297h80000gn/T/pip-build-env-p8fk30ek/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 253, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/ls/j8gt2mcd02s9z5yqbgt297h80000gn/T/pip-build-env-p8fk30ek/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 145, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 583, in <module>
          setup_package()
        File "setup.py", line 579, in setup_package
          setup(**metadata)
        File "/private/var/folders/ls/j8gt2mcd02s9z5yqbgt297h80000gn/T/pip-build-env-p8fk30ek/overlay/lib/python3.8/site-packages/numpy/distutils/core.py", line 137, in setup
          config = configuration()
        File "setup.py", line 477, in configuration
          raise NotFoundError(msg)
      numpy.distutils.system_info.NotFoundError: No lapack/blas resources found. Note: Accelerate is no longer supported.
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /Users/my-user/projects/my-project/.venv/bin/python /Users/my-user/projects/my-project/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/ls/j8gt2mcd02s9z5yqbgt297h80000gn/T/tmp6l431_j2 Check the logs for full command output.
```
</details>

**Comment by ilayn** [comment]
@kkozmic before anything the installer is unable to find any blas/lapack libraries. I have no idea what poetry is (I guess it is similar to conda) but could you please try to install libraries first? you can use `brew install` but then again no idea what poetry does.

**Comment by kkozmic** [comment]
@ilayn [Poetry](https://python-poetry.org/) is a package manager, like Bundler for Ruby, Gradle for Java, npm for Node...

The thing is, when running on Macos 10.15, or Linux things work just fine. That error only appears when installing on Macos 11

**Comment by ilayn** [comment]
As apple being apple, there was some dynamic linking changing stuff happening (see for example a similar issue for R https://github.com/sethrfore/homebrew-r-srf/issues/35#issuecomment-730396499) 

So your poetry machinery is not finding the system packages related to BLAS/LAPACK libraries. 

But yes that's your understanding is correct. Even then, it should be possible to build it on the fly on MacOS without any issues. Then again, I'm not a mac person so your guess is as good as mine. Let's see if more knowledgeable peepz can figure it out.

**Comment by jwischka** [comment]
@ilayn If you note my buildlog above, something is still not quite right in the scipy branch in terms of building from source on Big Sur, at least on Apple Silicon (but I suspect on Intel as well). The current numpy git (1.20-dev) does build under Big Sur, provided a native arm64 build of OpenBLAS is supplied. Even when OpenBLAS is present and provided in the site.cfg for scipy, the build fails. I suspect that some fixes have been made in the numpy tree that need to be imported into the scipy tree for the build to succeed.

**Comment by ilayn** [comment]
@jwischka Indeed, that seems so. We tend to get these crises every 6months or so when something gets updated; new Python version, new os, new compilers, new openblas version etc. So it seems that the most productive strategy is to get everyone stuck in the same point in the build procedure. Then one of us has an epiphany and things proceed. This one still didn't converge to the same point so that we can triangulate hence I'm trying to see what happens after we fix the missing blas libs parts.

**Comment by jwischka** [comment]
@ilayn Understood. I can possibly try to mess with things on my Intel Mac in a bit to see if the errors are similar. As I said above, I'm not super familiar with all the inner workings of scipy or its build process, but I'm happy to try to help out where I can to move things forward. Suggestions welcome!

**Comment by jwischka** [comment]
Update: Building on Intel Big Sur gives some similar issues:

>     openblas_lapack_info:
>     customize UnixCCompiler
>     customize UnixCCompiler
>     customize UnixCCompiler
>     C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64
> 
>     creating /var/folders/s0/99_fk7z51dqdx5951j9np_340000gn/T/tmpbj12njtj/var
>     creating /var/folders/s0/99_fk7z51dqdx5951j9np_340000gn/T/tmpbj12njtj/var/folders
>     creating /var/folders/s0/99_fk7z51dqdx5951j9np_340000gn/T/tmpbj12njtj/var/folders/s0
>     creating /var/folders/s0/99_fk7z51dqdx5951j9np_340000gn/T/tmpbj12njtj/var/folders/s0/99_fk7z51dqdx5951j9np_340000gn
>     creating /var/folders/s0/99_fk7z51dqdx5951j9np_340000gn/T/tmpbj12njtj/var/folders/s0/99_fk7z51dqdx5951j9np_340000gn/T
>     creating /var/folders/s0/99_fk7z51dqdx5951j9np_340000gn/T/tmpbj12njtj/var/folders/s0/99_fk7z51dqdx5951j9np_340000gn/T/tmpbj12njtj
>     compile options: '-c'
>     clang: /var/folders/s0/99_fk7z51dqdx5951j9np_340000gn/T/tmpbj12njtj/source.c
>     clang /var/folders/s0/99_fk7z51dqdx5951j9np_340000gn/T/tmpbj12njtj/var/folders/s0/99_fk7z51dqdx5951j9np_340000gn/T/tmpbj12njtj/source.o -L/opt/OpenBLAS/lib -lopenblas -o /var/folders/s0/99_fk7z51dqdx5951j9np_340000gn/T/tmpbj12njtj/a.out
>     Undefined symbols for architecture x86_64:
>       "_zungqr_", referenced from:
>           _main in source.o
>     ld: symbol(s) not found for architecture x86_64
>     clang: error: linker command failed with exit code 1 (use -v to see invocation)
>       NOT AVAILABLE
> 
>     openblas_clapack_info:
>     customize UnixCCompiler
>     customize UnixCCompiler
>     customize UnixCCompiler
>     C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64

So it does look like a Big Sur problem, not a specific Apple Silicon problem.

**Comment by ernestoarbitrio** [comment]
Still failing here with pyenv. The only way I found to fix this issue is using `miniconda` / `anaconda` distribution. On the conda envs it goes like a charm. TBH i don't really know why such a big difference of behaviour between these two python distro. 🤷🏽‍♂️

**Comment by tylerjereddy** [comment]
> TBH i don't really know why such a big difference of behaviour between these two python distro. 

They don't use the same binaries for installation, among other things

**Comment by iamDecode** [comment]
Fwiw, I managed to install `scipy` on Big Sur (Intel Macbook) by using the compatibility mode, in which macOS will report being version 10.16 instead of 11.0:

```
export SYSTEM_VERSION_COMPAT=1
> sw_vers -productVersion
10.16
```

**Comment by Pungys** [comment]
updating pip did the trick for me.

**Comment by timkofu** [comment]
Also, when using Poetry, first updating pip then running `add` or `install` works.

**Comment by emlai** [comment]
For me scipy 1.4.1 failed with `No lapack/blas resources found.`

scipy 1.6.0 installed succesfully.

**Comment by V0lantis** [comment]
For me macOS Big Sur, pip 20.3.3, SciPy v1.6.0, same error either with pip or with python (`python setup.py build`).
I am using OpenBlas.

**Comment by denizdogan** [comment]
I found this thread looking for a way to install librosa on macOS Big Sur 11.1 on Macbook Pro Intel. librosa depends on llvmlite, numpy, and **scipy** and I had various issues installing each of those dependencies. Finally, I have found a way that works for me and hopefully, this will help someone else.

First of all, you will need to install `llvm@9` and `openblas` from Homebrew:

```console
$ brew install llvm@9 openblas
```

After that, you will need to pass a bunch of environment variables to the `poetry install librosa` command, as described here and other places on the web:

```console
$ SYSTEM_VERSION_COMPAT=1 \
LDFLAGS="-L/usr/local/opt/openblas/lib -L/usr/local/opt/llvm@9/lib -Wl,-rpath,/usr/local/opt/llvm@9/lib" \
CPPFLAGS="-I/usr/local/opt/openblas/include -I/usr/local/opt/llvm/include" \
LLVM_CONFIG=$(brew --prefix llvm@9)/bin/llvm-config \
OPENBLAS="$(brew --prefix openblas)" \
poetry add librosa
```

Done!

In case you're having issues, here's the exact versions of everything I'm using:

- llvm@9: stable 9.0.1 (bottled) [keg-only]
- openblas: stable 0.3.13 (bottled), HEAD [keg-only]
- GNU Fortran (Homebrew GCC 10.2.0_3) 10.2.0
- Apple clang version 12.0.0 (clang-1200.0.32.28)
- Python 3.8.7
- Poetry version 1.1.4
- pip 21.0

**Comment by jmorenobl** [comment]
Hello!
I could finally install scipy on Mac OSX Big Sur thanks to @denizdogan. In my case, since I only needed scipy this is what I did.

`brew install openblas`

Then I executed the following:

`
SYSTEM_VERSION_COMPAT=1 \
LDFLAGS="-L/usr/local/opt/openblas/lib" \
CPPFLAGS="-I/usr/local/opt/openblas/include" \
OPENBLAS="$(brew --prefix openblas)" \
poetry add scipy
`
And it got installed successfully!

**Comment by V0lantis** [comment]
> SYSTEM_VERSION_COMPAT=1 \
> LDFLAGS="-L/usr/local/opt/openblas/lib" \
> CPPFLAGS="-I/usr/local/opt/openblas/include" \
> OPENBLAS="$(brew --prefix openblas)" \
> poetry add scipy
> ```
> 
> And it got installed successfully!

Using poetry, I have this issue (not used to work with poetry):
```
  PyProjectException

  [tool.poetry] section not found in /Users/arthur/Documents/Développement/python/scipy/pyproject.toml

  at ~/.poetry/lib/poetry/_vendor/py3.9/poetry/core/pyproject/toml.py:55 in poetry_config
      51│     def poetry_config(self):  # type: () -> Optional[TOMLDocument]
      52│         if self._poetry_config is None:
      53│             self._poetry_config = self.data.get("tool", {}).get("poetry")
      54│             if self._poetry_config is None:
    → 55│                 raise PyProjectException(
      56│                     "[tool.poetry] section not found in {}".format(self._file)
      57│                 )
      58│         return self._poetry_config
      59│ 
```

**Comment by denizdogan** [comment]
@V0lantis You don't need Poetry to get it working, pip should be fine. :) Replace `poetry add X` with `pip install X` and hopefully, that should work. If you still want to use Poetry, you should run `poetry init`, but better yet, just read the official Poetry documentation, it's pretty simple: https://python-poetry.org/docs/basic-usage/

**Comment by V0lantis** [comment]
Ok thank you for your answers, it finally worked for me (MacOs BigSur).
I don't know how I solved it but here is what I have done : 

- Enabling a virtualenv (`virtualenv .venv`)
- Installing all the needed libraries (last version of numpy==1.20.0rc2)
- Upgrading my gcc compiler
- make an in-place build.

Somehow it worked, so I am happy

**Comment by pierreia** [comment]
> For me macOS Big Sur, pip 20.3.3, SciPy v1.6.0, same error either with pip or with python (`python setup.py build`).
> I am using OpenBlas.
> I was able to remove this error following this [comment](https://github.com/scipy/scipy/issues/13361#issuecomment-756347908):
> 
> ```shell
> pip uninstall numpy
> python -m pip install -i https://pypi.anaconda.org/multibuild-wheels-staging/simple numpy==1.20.0rc2
> pip install . --no-build-isolation
> ```
> 
> But I ended up with this error
> 
> ```
> ERROR: Failed building wheel for scipy
> Failed to build scipy
> ERROR: Could not build wheels for scipy which use PEP 517 and cannot be installed directly
> ```
> 
> Anybody knows why?

I got the same error while trying to install scipy on Mac Apple Silicon with ```pip install scipy```. 
When i try to install scipy from source, I have 
```
Traceback (most recent call last):
  File "setup.py", line 605, in <module>
    setup_package()
  File "setup.py", line 601, in setup_package
    setup(**metadata)
  File "/Users/PycharmProjects/Project/venv/lib/python3.8/site-packages/numpy/distutils/core.py", line 137, in setup
    config = configuration()
  File "setup.py", line 516, in configuration
    raise NotFoundError(msg)
numpy.distutils.system_info.NotFoundError: No BLAS/LAPACK libraries found. Note: Accelerate is no longer supported.
To build Scipy from sources, BLAS & LAPACK libraries need to be installed.
See site.cfg.example in the Scipy source directory and
https://docs.scipy.org/doc/scipy/reference/building/index.html for details.
```

Did anyone succeed in installing scipy on a Mac M1?

**Comment by the-lagrangian** [comment]
> Then I executed the following:
> 
> ```
> SYSTEM_VERSION_COMPAT=1 \
> LDFLAGS="-L/usr/local/opt/openblas/lib" \
> CPPFLAGS="-I/usr/local/opt/openblas/include" \
> OPENBLAS="$(brew --prefix openblas)" \
> poetry add scipy
> ```
> 
> And it got installed successfully!

@jmorenobl thanks for this! I will note for others that this worked only with my terminal in Rosetta mode, not in M1 mode.

**Comment by pikeas** [comment]
Intel Mac, Big Sur 11.2, pip 21.0.1 (also 20.3.1), poetry 1.1.4, Python 3.9.1.

I hit this same issue while updating a poetry-managed virtualenv today:

```
numpy.distutils.system_info.NotFoundError: No BLAS/LAPACK libraries found. Note: Accelerate is no longer supported.
To build Scipy from sources, BLAS & LAPACK libraries need to be installed.
```

After many years of reporting its system version as 10.x, macOS Big Sur reports itself as version 11.x. This breaks various things, including some parts of the Python packaging ecosystem. While we wait for package maintainers to publish 11.x wheels (no rush and we appreciate what you do!), any workaround that maps 10.x forward to 11.x, or maps 11.x back to 10.x, should fix the issue.

The easiest option I've found is `SYSTEM_VERSION_COMPAT=1 <poetry|pip|pyenv|etc> <command>`. This env var causes macOS to return a version string of 10.x (currently 10.16) instead of 11.x. For scipy, this will find the wheel `scipy-1.6.1-cp39-cp39-macosx_10_9_x86_64.whl` instead of building from source.

**Comment by pierreia** [comment]
I successfully installed it on Big Sur with M1 Architecture, by using miniconda! Just by doing `conda install scipy` ....!

**Comment by cuent** [comment]
> Fwiw, I managed to install `scipy` on Big Sur (Intel Macbook) by using the compatibility mode, in which macOS will report being version 10.16 instead of 11.0:
> 
> ```
> export SYSTEM_VERSION_COMPAT=1
> > sw_vers -productVersion
> 10.16
> ```

This made the trick! Thanks so much for your answer... It works!

**Comment by truedaz** [comment]
I can instal on BigSur with the above but I get tis error when trying to run a script that worked on Catalina:
'''cannot import name '_ccallback_c' from 'scipy._lib' (/Library/Python/3.8/site-packages/scipy/_lib/__init__.py)'''
on code
'''from scipy.signal import argrelextrema'''

**Comment by drinkbeer** [comment]
> Fwiw, I managed to install `scipy` on Big Sur (Intel Macbook) by using the compatibility mode, in which macOS will report being version 10.16 instead of 11.0:
> 
> ```
> export SYSTEM_VERSION_COMPAT=1
> > sw_vers -productVersion
> 10.16
> ```

This works for me (Big Sur).

**Comment by mccarthydanielle** [comment]
> > Fwiw, I managed to install `scipy` on Big Sur (Intel Macbook) by using the compatibility mode, in which macOS will report being version 10.16 instead of 11.0:
> > ```
> > export SYSTEM_VERSION_COMPAT=1
> > > sw_vers -productVersion
> > 10.16
> > ```
> 
> This works for me (Big Sur).

me too!

**Comment by davcamer** [comment]
macOS 11.3.1
Python 3.9.4
pyenv 1.2.27
pipenv 2020.11.15
pip 21.1.1

Trying to `pipenv install scipy` as a dependency for `pipenv install lightgbm`.

Only the `export SYSTEM_VERSION_COMPAT=1` solution worked for me. Without this envvar, pipenv was falling back to building from source instead of downloading a wheel.

I confirmed the pip version in the virtual environment with `pipenv run pip --version`, and pinned it [as described elsewhere](https://github.com/pypa/pipenv/issues/3142#issuecomment-831378235) with `export VIRTUALENV_PIP=21.1.1`, but this did not help with the `pipenv install scipy`.

**Comment by samcdavid** [comment]
If you're using poetry, I was able to successfully install by running `poetry self update` and `poetry run pip install --upgrade pip` though you don't _have_ to update poetry.

After this `poetry install` worked just fine for me and I was able to run the project just fine.

**Comment by tommydangerous** [comment]
Wow, this worked. Thank you:

Install `openblas`:

```
$ brew install openblas
```

I used `pip3` to install `scipy`
```
$ SYSTEM_VERSION_COMPAT=1 \
LDFLAGS="-L/usr/local/opt/openblas/lib" \
CPPFLAGS="-I/usr/local/opt/openblas/include" \
OPENBLAS="$(brew --prefix openblas)" \
pip3 install scipy
```

Success!!!!
```
Collecting scipy
  Downloading scipy-1.6.3-cp38-cp38-macosx_10_9_x86_64.whl (30.8 MB)
     |████████████████████████████████| 30.8 MB 128 kB/s
Requirement already satisfied: numpy<1.23.0,>=1.16.5 in ./env/lib/python3.8/site-packages (from scipy) (1.19.2)
Installing collected packages: scipy
Successfully installed scipy-1.6.3
```

**Comment by cSDes1gn** [comment]
@tommydangerous 's solution worked for me on apple silicon. cheers!

**Comment by aguschin** [comment]
For me using python 3.9.5 instead of 3.10 solved the issue.

**Comment by carismoses** [comment]
A lot of the solutions listed here were not working for me. What ultimately worked was:
```
brew install scipy
```
It installed python3.9 in the process at this location ```/opt/homebrew/Cellar/python@3.9/3.9.6/bin/python3```, so I have to run this python executable to use ```import scipy```.

**Comment by tinkerware** [comment]
We ran into this recently as well (using scipy 1.7.0 and Python 3.7.10 together), and what worked for us was:

  - `xcode-select --install` before anything, with latest XCode from App Store
  - `brew install pyenv`
  - `pyenv install 3.7.10 && pyenv global 3.7.10`
  - `pip install scipy`

We actually use `Pipenv`, and it helped to split `pipenv lock` and `pipenv sync`, though likely due to our other dependencies.

**Comment by carismoses** [comment]
> None of the solutions listed here were working for me. What ultimately worked was:
> 
> ```
> brew install scipy
> ```
> 
> It installed python3.9 in the process at this location `/opt/homebrew/Cellar/python@3.9/3.9.6/bin/python3`, so I have to run this python executable to use `import scipy`.

This actually didn't work... When I tried to `import sklearn` the import failed. @tommydangerous's solution worked for me!

**Comment by hanpham32** [comment]
> I successfully installed it on Big Sur with M1 Architecture, by using miniconda! Just by doing `conda install scipy` ....!

This also works for me!

**Comment by kikicrisp** [comment]
> > I think this is solved with the new release of pip, which added support for macOSx 11 to install wheels with a 10_9 tag.
> 
> Updating pip version to `21.3.1` solves this problem for me


If you're using Python 3.10.0, updating pip to '21.3.1' still doesn't work. The ultimate solution is:

1. install xcode
2. install homebrew
3. use homebrew install pyenv
4. use pyenv to install python 3.9.0
5. vim .zshrc  -> export PATH="$(pyenv root)/shims:$PATH" ->esc->:wq
6. pyenv global 3.9.0
7. check if pip under python 3.9.0 folder with: pip --version(upgrade to 21.3.1 if not)
8. pip install -U scikit-learn

Hope this can help people like me, spent 3 days looking for solution, finally got it solved!

**Comment by TylerADavis** [comment]
I believe that newer versions of NumPy have reintroduced support for accelerate on Mac (see https://github.com/numpy/numpy/pull/18874). Would updating the version of NumPy that scipy depends on at build time help to resolve this issue?

**Comment by rgommers** [comment]
No, we cannot use Accelerate in SciPy, and the NumPy wheels don't use Accelerate (all wheels ship with OpenBLAS). So there's nothing that changed with the reintroduction of Accelerate besides from-source builds.

**Comment by msarrias** [comment]
> I can instal on BigSur with the above but I get tis error when trying to run a script that worked on Catalina: `cannot import name '_ccallback_c' from 'scipy._lib' (/Library/Python/3.8/site-packages/scipy/_lib/__init__.py)'` on code `from scipy.signal import argrelextrema`

Hi, did you manage to fix it? I'm having the same problem.

**Comment by rgommers** [comment]
This is all fixed in `pip`. Let's document the solutions, there are two:

1. Upgrade to most recent version of `pip` (preferred).
2. For older versions of `pip`, the problem can be worked around by `export SYSTEM_VERSION_COMPAT=1`.

This issue was for macOS Big Sur on _Intel_ hardware. There are separate issues for `arm64` (M1) hardware. I'll close this issue.

**Comment by techkuz** [comment]
update pip

**Comment by inspiralpatterns** [comment]
It still does not work with Python `3.10.1` even when updating `pip` to the latest version.
It does work if I revert to Python `3.9.10` instead. Such a pity, I so want to use structural pattern matching!

**Comment by rgommers** [comment]
There are Python 3.10 wheels for `x86_64` and `arm64` at https://pypi.org/project/scipy/1.8.0/#files. The only thing that won't be supported is if you're on macOS 11.x and want `arm64` scipy. Upgrade to macOS 12 and `pip install scipy` will work.
