### ISSUE TITLE
BUG: optimize.shgo: not using options

### ISSUE THREAD

**Issue by mamerchandmedi** [scipy/scipy#13974]
hi, 

I am using optimize.shgo to find the minimum of def f(x): x1,x2=x return M1(x1,x2)**2+M2(x1,x2)**2
where M1 and M2 are two complicated function which take a lot of time (9 secs) to evaluate. 
I notice that it takes a long time for optimize.shgo to finish (about 1hr) so I wan to use options dictionary to make it stop sooner then use the solution as initial guess for other minimizer but it seems that optimize.shgo doesn't care what options I give it. In fact even writing iters=0 it still runs!

can anyone here point me in the right direction?

**Comment by AtsushiSakai** [comment]
Hi. Thank you for reporting. Could you share us your code example reproducing the issue?.

**Comment by mamerchandmedi** [comment]
Hello. Here is the input. M1 and M2 are defined as integrals of other functions so are integrated numerically.

def solve_moments(x):
    vw=x[0]
    Lh=x[1]
    return M1(vw,L)**2+M2(vw,L)**2
L=5/100
bnds = ((0.01, 0.99), (0.001*L, 10*L))
#opt_dict={"maxfev":2,"f_min":0,"f_tol":10e-1,"maxiter":1,"maxtime":1}
minimum=optimize.shgo(func=solve_moments,bounds=bnds,n=1, iters=0,options=None)


Here is the output: 

fun: 0.054116716357765826
    funl: array([0.05411672])
 message: 'Optimization terminated successfully.'
    nfev: 324
     nit: 2
   nlfev: 319
   nlhev: 0
   nljev: 55
 success: True
       x: array([0.76707782, 0.02817877])
      xl: array([[0.76707782, 0.02817877]])
me_bubble.guess

**Comment by tupui** [comment]
> I am using optimize.shgo to find the minimum of def f(x): x1,x2=x return M1(x1,x2)**2+M2(x1,x2)**2
> where M1 and M2 are two complicated function which take a lot of time (9 secs) to evaluate.
> I notice that it takes a long time for optimize.shgo to finish (about 1hr) so I wan to use options dictionary to make it stop sooner then use the solution as initial guess for other minimizer but it seems that optimize.shgo doesn't care what options I give it. In fact even writing iters=0 it still runs!

`iters=0` is a known bug. There are fixes for this on the develop version (for `sampling_method="sobol"`) but we still need to work on it. The way `n` works if a bit different with `sampling_method="simplicial"` than `sampling_method="sobol"` so the number do not match exactly.

@Stefan-Endres can you help here? I am not sure if this issue is not redundant with the ones we already have.

**Comment by Stefan-Endres** [comment]
Hello, yes the `iters` bug has been fixed in the [upstream](https://github.com/Stefan-Endres/shgo) there is also a new stopping criteria called `maxtime` that can be passed to options which will stop the routine after a certain amount of time. I nearly done cleaning the code and documenting the cache library I aim to open the PR to scipy before the end of the week.

**Comment by tupui** [comment]
> Hello, yes the `iters` bug has been fixed in the [upstream](https://github.com/Stefan-Endres/shgo) there is also a new stopping criteria called `maxtime` that can be passed to options which will stop the routine after a certain amount of time. I nearly done cleaning the code and documenting the cache library I aim to open the PR to scipy before the end of the week.

Thanks for the prompt reply @Stefan-Endres. We will then link all these issues with your PR then, great! Let me know if I can help you with anything.

**Comment by mamerchandmedi** [comment]
Hello again,

From the comments above it seems that I still cannot use the options {"maxfev":2,"f_min":0,"f_tol":10e-1,"maxiter":1,"maxtime":1}, right?
also the iter and n options only have an effec IF one uses sampling_method="sobol".

best regards,
Marco

**Comment by tupui** [comment]
> Hello again,
> 
> 
> 
> From the comments above it seems that I still cannot use the options {"maxfev":2,"f_min":0,"f_tol":10e-1,"maxiter":1,"maxtime":1}, right?
> 
> also the iter and n options only have an effec IF one uses sampling_method="sobol".
> 
> 
> 
> best regards,
> 
> Marco
> 
> 

I would have to check the code, but there are some checks in the tests regarding these options. As we said, the interface is still being worked. We will for sure see to check that with the upcoming changes. But I cannot guarantee that this would be ready for the next release as we should fix the release in a few weeks now.
