### ISSUE TITLE
threads.h not available on OpenBSD, scipy assumes it is present

### ISSUE THREAD

**Issue by dimpase** [scipy/scipy#14364]
My issue is about building scipy on OpenBSD.

#### Error message:

```
  creating build/temp.openbsd-6.9-amd64-3.8/build/src.openbsd-6.9-amd64-3.8/build/src.openbsd-6.9-amd64-3.8/scipy/integrate
  compile options: '-DNO_ATLAS_INFO=1 -DHAVE_CBLAS -I/home/dima/sagetrac-mirror/local/include -Ibuild/src.openbsd-6.9-amd64-3.8/build/src.openbsd-6.9-amd64-3.8/scipy/integrate -I/home/dima/sagetrac-mirror/local/
lib/python3.8/site-packages/numpy/core/include -Ibuild/src.openbsd-6.9-amd64-3.8/numpy/distutils/include -I/home/dima/sagetrac-mirror/local/include -I/usr/local/include/python3.8 -c'
  extra options: '-msse -msse2 -msse3'
  clang: build/src.openbsd-6.9-amd64-3.8/scipy/integrate/vodemodule.c
  In file included from build/src.openbsd-6.9-amd64-3.8/scipy/integrate/vodemodule.c:16:
  In file included from build/src.openbsd-6.9-amd64-3.8/build/src.openbsd-6.9-amd64-3.8/scipy/integrate/fortranobject.h:13:
  In file included from /home/dima/sagetrac-mirror/local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:4:
  In file included from /home/dima/sagetrac-mirror/local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
  In file included from /home/dima/sagetrac-mirror/local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:1944:
  /home/dima/sagetrac-mirror/local/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_
API NPY_1_7_API_VERSION" [-W#warnings]
  #warning "Using deprecated NumPy API, disable it with " \
   ^
  build/src.openbsd-6.9-amd64-3.8/scipy/integrate/vodemodule.c:88:10: fatal error: 'threads.h' file not found
  #include <threads.h>
           ^~~~~~~~~~~
  1 warning and 1 error generated.
```

#### Scipy/Numpy/Python version information:

building scipy 1.6.3
```
Python 3.8.8 (default, Apr 19 2021, 10:23:47) 
[Clang 10.0.1 ] on openbsd6
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, numpy; print(numpy.__version__, sys.version_info)
1.20.3 sys.version_info(major=3, minor=8, micro=8, releaselevel='final', serial=0)
```

**Comment by peterbell10** [comment]
Looks like numpy/numpy#18179 and `vode` is an f2py module. This seems to have been fixed in [NumPy 1.20.3](https://github.com/numpy/numpy/releases/tag/v1.20.3) though. Are you building SciPy with `pip`? If so we might be using an old version of NumPy which doesn't have the bug fixed.

**Comment by dimpase** [comment]
We are building SciPy with pip using the local copy of NumPy 1.20.3. So it's probably not fixed there. I'll have a look at reproducing numpy/numpy#18179

**Comment by dimpase** [comment]
Indeed, the test in numpy/numpy#18179 still fails on NumPy 1.20.3.

**Comment by peterbell10** [comment]
>don't have any other than NumPy 1.20.3 installed anywhere on the box

This is irrelevant. `pip` build isolation creates and new virtual environment for the build and installs the dependencies listed in `pyproject.toml`.
https://github.com/scipy/scipy/blob/5fba81b49065cd929dbd8df64a43a4d57fe0c21e/pyproject.toml#L33-L36

>besides, you can just have a look at at the patch on numpy/numpy#18179 and see that it did not make it in the source of NumPy 1.20.3.

It's present in the maintenance branch and pre-dates the 1.20.3 release by around a month, so this seems unlikey.
https://github.com/numpy/numpy/commits/maintenance/1.20.x/numpy/f2py/cfuncs.py

**Comment by dimpase** [comment]
In this case one can [see from the log](https://users.ox.ac.uk/~coml0531/tmp/scipy-1.6.3.log) of the build that nothing like installing another version of NumPy just to build SciPy is taking place.

Besides, I tried the test from  numpy/numpy#18179 with my supposedly fixed NumPy 1.20.3, and it still fails: https://github.com/numpy/numpy/issues/18179#issuecomment-876269573

**Comment by peterbell10** [comment]
Okay, if it's not build isolation then there's nothing on SciPy's side effecting this. I suggest opening a NumPy issue with more details of your environment and the libc your using.

**Comment by dimpase** [comment]
I've opened numpy/numpy#19437

**Comment by sandeep-gh** [comment]
What is the status of this bug? I compiled  scipy with numpy 1.21.4 using following command
``python3 -m pip install -vv  --no-build-isolation  scipy```. 
I get the same error, even though it was claimed in numpy github issue that this has been fixed in 1.21.4.

**Comment by dimpase** [comment]
> What is the status of this bug? I compiled scipy with numpy 1.21.4 using following command ``python3 -m pip install -vv --no-build-isolation scipy```. I get the same error, even though it was claimed in numpy github issue that this has been fixed in 1.21.4.

If you still can reproduce https://github.com/numpy/numpy/issues/19437 then it's numpy's issue (note that https://github.com/numpy/numpy/issues/19437 is still marked as open).

**Comment by sandeep-gh** [comment]
My bad. I can reproduce this issue with numpy.

**Comment by barracuda156** [comment]
Still broken for macOS though, where macros work in such a way as to simply assume `threads.h` is present based on C11 version, which is wrong: compiler does not provide this header, it is supplied or not by the OS libc.

**Comment by dimpase** [comment]
> Still broken for macOS though

Only with "real" gcc.
