### ISSUE TITLE
BUG: RBFInterpolator fails when calling it with a slice of a (1, n) array

### ISSUE THREAD

**Issue by treverhines** [scipy/scipy#14420]
RBFInterpolator has a bug where it throws an error when calling it with a slice of a (1, n) array. The below code reproduces the error:

```python
import numpy as np                                       
from scipy.interpolate import RBFInterpolator            
                                                         
y = np.random.random((3, 2))                             
d = np.random.random((3,))                               
x = np.random.random((1, 3))[:, :2]                      
RBFInterpolator(y, d)(x) 
```

which throws this error:
```
Traceback (most recent call last):
  File "rbfinterp_bug.py", line 7, in <module>
    RBFInterpolator(y, d)(x)
  File "/home/hinest/miniconda3/lib/python3.8/site-packages/scipy/interpolate/_rbfinterp.py", line 416, in __call__
    out = _evaluate(
TypeError: Invalid call to pythranized function `_evaluate(float64[:, :] (reshaped), float64[:, :], str, float, int64[:, :], float64[:], float64[:], float64[:, :] (reshaped))'
Candidates are:

    - _evaluate(float[:,:], float[:,:], str, float, int[:,:], float[:], float[:], float[:,:])

```
The issue is that `x` has shape (1, 2) and stride (24, 8), which allows it to pass through ` x = np.asarray(x, dtype=float, order="C")` at [this](https://github.com/scipy/scipy/blob/b7c79ab69b1ad63733c2f051ad68f969bb3a35ec/scipy/interpolate/_rbfinterp.py#L404) line of `RBFInterpolator.__call__` because it still is C-contiguous, but pythran throws an error saying that `x` is reshaped. @serge-sans-paille is this the expected behavior for pythran? If so, is there a better way to sanitize the input for pythranized functions than `np.asarray` with `order` specified?

**Comment by rgommers** [comment]
This is a tricky issue that we may see in other places. It turns out that the error message is somewhat cryptic, but the `(reshaped)` in the signature mismatch means that the input is either:
- a view, or
- a non-contiguous array, or 
- a Fortran-ordered array

The normal expectation for SciPy code is that all of those work. The reason Pythran does accept them is that it doesn't have all the machinery to do such arbitrary striding, and if it make a copy internally then the semantics of in-place operations would change. One potential solution @serge-sans-paille, @charlotte12l and I just discussed is have a way to tell Pythran to support all such input (e.g., `#pythran: allow-strided-and-views`). SciPy is not the only Pythran user, but from SciPy's point of view mutating input arrays is anyway an anti-pattern, so it'd be much better to not have to do checks for contiguity on the Python side.

**Comment by rgommers** [comment]
The type mismatch hint is coming from https://github.com/serge-sans-paille/pythran/blob/master/pythran/pythonic/python/core.hpp#L83, relevant part:

```C++
      if ((PyArray_FLAGS(arr) & NPY_ARRAY_F_CONTIGUOUS) &&
          ((PyArray_FLAGS(arr) & NPY_ARRAY_C_CONTIGUOUS) == 0) &&
          (PyArray_NDIM(arr) > 1)) {
        oss << " (with unsupported column-major layout)";
      } else if (PyArray_BASE(arr)) {
        oss << " (reshaped)";
      } else {
        auto const *stride = PyArray_STRIDES(arr);
        auto const *dims = PyArray_DIMS(arr);
        long current_stride = PyArray_ITEMSIZE(arr);
        for (long i = PyArray_NDIM(arr) - 1; i >= 0; i--) {
          if (stride[i] != current_stride) {
            oss << " (strided)";
            break;
          }
          current_stride *= dims[i];
        }
      }
```
So actually the Fortran ordering has a separate message.

**Comment by rgommers** [comment]
A more useful error message would be something like `"(is a view)"`.

**Comment by rgommers** [comment]
> If so, is there a better way to sanitize the input for pythranized functions than `np.asarray` with `order` specified?

There's no single function call that does it all it looks like, it needs:
```python
if x.base is not None:
    x = x.copy()
```

**Comment by treverhines** [comment]
I thought pythran _does_ support views. If you look at the above error message, there is a second array labeled as "reshaped", which is the `coeffs` argument. I believe that array is always a view and pythran does not throw an error for it.

**Comment by rgommers** [comment]
I'm getting a little lost in the signature comparison code, but I think the reason is that `self._coeffs` is a simple transpose of its `.base`. There is some special-casing of simple transposed arrays (e.g. https://github.com/serge-sans-paille/pythran/blob/4cd74b208616127f4055c9842476ec02540977d6/pythran/spec.py#L531).

I could well be wrong though, let's see if @serge-sans-paille has something more informative to say:)

**Comment by rgommers** [comment]
Your example works when I use `x = np.random.random((2, 1)).T`, which is also a view.

**Comment by rgommers** [comment]
From the Pythran docs that describe argument types:
```python
              | argument_type []+    # this is a ndarray, C-style
              | argument_type [::]+    # this is a strided ndarray
              | argument_type [:,...,:]+ # this is a ndarray, Cython style
              | argument_type [:,...,3]+ # this is a ndarray, some dimension fixed
```
The not-accepting-views behavior is undocumented, it should be in https://pythran.readthedocs.io/en/latest/MANUAL.html#limitations until there's a way to allow passing them in.

**Comment by treverhines** [comment]
I believe the error is being raised for my above example because of this check in pythran:
https://github.com/serge-sans-paille/pythran/blob/5a144994c8a687266fa14980b4a85f6a7a181954/pythran/pythonic/types/ndarray.hpp#L1542

which I believe is checking the strides and shape to verify that the array is C-contiguous. But I suspect that pythran is being too strict with this check, and it is raising an error for arrays that are still C-contiguous (like the array in my above example). This diff appears to resolve the issue (for my above example at least):

   ```diff --git a/pythran/pythonic/types/ndarray.hpp b/pythran/pythonic/types/ndarray.hpp
index aea43f3d2..5c6637097 100644
--- a/pythran/pythonic/types/ndarray.hpp
+++ b/pythran/pythonic/types/ndarray.hpp
@@ -1539,7 +1539,7 @@ bool from_python<types::ndarray<T, pS>>::is_convertible(PyObject *obj)
   for (long i = std::tuple_size<pS>::value - 1; i >= 0; i--) {
     if (stride[i] == 0 && dims[i] == 1) {
       // happens when a new dim is added though None/newaxis
-    } else if (stride[i] != current_stride)
+    } else if (stride[i] != current_stride && dims[i] > 1)
       return false;
     current_stride *= dims[i];
   }
```

Disclaimer: I am not at all comfortable with the pythran source code and I am not sure what the repercussions are for the above change.

**Comment by treverhines** [comment]
If there is not a quick fix on the pythran side, then I think a solution on the scipy side would be to sanitize the `RBFInterpolator` array arguments `x`, `y`, and `d` with something like

```python
x = np.asarray(x, dtype=float, order='C')
x = np.ndarray(x.shape, dtype=float, buffer=x)
``` 
The second step just rewrites the `strides` attribute for `x` so that pythran considers it a valid array. The strides attribute is only an issue when an axis of `x` has length 1 or 0 (as mentioned here  https://numpy.org/devdocs/reference/c-api/array.html#basic-array-flags)

**Comment by serge-sans-paille** [comment]
> I believe the error is being raised for my above example because of this check in pythran:
> https://github.com/serge-sans-paille/pythran/blob/5a144994c8a687266fa14980b4a85f6a7a181954/pythran/pythonic/types/ndarray.hpp#L1542
> 
> which I believe is checking the strides and shape to verify that the array is C-contiguous. But I suspect that pythran is being too strict with this check, and it is raising an error for arrays that are still C-contiguous (like the array in my above example). This diff appears to resolve the issue (for my above example at least):
> 
> ```diff
> index aea43f3d2..5c6637097 100644
> --- a/pythran/pythonic/types/ndarray.hpp
> +++ b/pythran/pythonic/types/ndarray.hpp
> @@ -1539,7 +1539,7 @@ bool from_python<types::ndarray<T, pS>>::is_convertible(PyObject *obj)
> for (long i = std::tuple_size<pS>::value - 1; i >= 0; i--) {
>   if (stride[i] == 0 && dims[i] == 1) {
>     // happens when a new dim is added though None/newaxis
> -    } else if (stride[i] != current_stride)
> +    } else if (stride[i] != current_stride && dims[i] > 1)
>     return false;
>   current_stride *= dims[i];
> }
> ```
> 
> Disclaimer: I am not at all comfortable with the pythran source code and I am not sure what the repercussions are for the above change.

Could you open an issue on the pythran side with a simple reproducer (including the call site?)
I'd be happy to investigate your patch :-)

**Comment by treverhines** [comment]
This issue is resolved when building with the latest version of pythran (since this commit https://github.com/serge-sans-paille/pythran/commit/3f9090067179e00b1923ae57deadb6cfbf21b1d3).

**Comment by rgommers** [comment]
Thanks @treverhines! Let's leave this issue open and marked for 1.7.2 until we have bumped the minimum Pythran version in `pyproject.toml` and in CI after the next release.

**Comment by rgommers** [comment]
https://github.com/serge-sans-paille/pythran/commit/3f9090067179e00b1923ae57deadb6cfbf21b1d3 is part of pythran `0.10.0` and not in `0.9.12` - so this is not fixed for SciPy `1.7.2` or `1.7.3`. We'll bump this to `1.8.0`.

**Comment by rgommers** [comment]
Fixed by gh-15322, which will be released in `1.8.0`.
