### ISSUE TITLE
BUG: Interphinxs with scipy 1.8.0 doesn't work.

### ISSUE THREAD

**Issue by tiagofrepereira2012** [scipy/scipy#15574]
### Describe your issue.

It's no possible to intersphinx with scipy 1.8.0
The inventory file is https://docs.scipy.org/doc/scipy-1.8.0/reference/objects.inv unavailable

I'm wondering how can I get this fixed.

Thanks for any feedback

### Reproducing Code Example

```python
wget https://docs.scipy.org/doc/scipy-1.8.0/reference/objects.inv
--2022-02-11 09:43:04--  https://docs.scipy.org/doc/scipy-1.8.0/reference/objects.inv
Resolving docs.scipy.org (docs.scipy.org)... 50.17.248.72
Connecting to docs.scipy.org (docs.scipy.org)|50.17.248.72|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-02-11 09:43:04 ERROR 404: Not Found.
```

### Error message

```shell
--2022-02-11 09:43:04--  https://docs.scipy.org/doc/scipy-1.8.0/reference/objects.inv
Resolving docs.scipy.org (docs.scipy.org)... 50.17.248.72
Connecting to docs.scipy.org (docs.scipy.org)|50.17.248.72|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-02-11 09:43:04 ERROR 404: Not Found.
```
```


### SciPy/NumPy/Python version information

1.8.0 1.21.5 sys.version_info(major=3, minor=8, micro=12, releaselevel='final', serial=0)

**Comment by melissawm** [comment]
Hello, @tiagofrepereira2012 - you can update the intersphinx URL for SciPy in your `conf.py` file to read https://docs.scipy.org/doc/scipy - this should resolve the issue. (see, for example https://github.com/numpy/numpy/pull/21016/files)

**Comment by tiagofrepereira2012** [comment]
Hi @melissawm,

Thanks for the quick feedback, but I still can't fetch a specific intersphinx version.
For instance, I have 404 with this address https://docs.scipy.org/doc/scipy-1.8.0/objects.inv, or this one https://docs.scipy.org/doc/scipy-1.7.3/objects.inv 

The 1.7.1 works: https://docs.scipy.org/doc/scipy-1.7.1/objects.inv 

However, this one works (https://docs.scipy.org/doc/scipy/reference/objects.inv). Which is the 1.8.0 btw.

**Comment by tiagofrepereira2012** [comment]
Not all intersphinx artifacts are available.

**Comment by melissawm** [comment]
Ok - then I suppose this is related to #14267, maybe the discussion can be moved there.

**Comment by tiagofrepereira2012** [comment]
Oh, thanks.
I haven't seen this one.

I'll close this one then.

Thanks again
