### ISSUE TITLE
Build warnings "-pie being ignored"

### ISSUE THREAD

**Issue by lucascolley** [scipy/scipy#19736]
On `python dev.py build` I see a wall of warnings all with the same error message:

```shell
[11/1604] Linking target scipy/_lib/_fpumode.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[12/1604] Linking target scipy/_lib/_test_ccallback.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
[42/1604] Linking target scipy/_lib/_test_deprecation_call.cpython-310-darwin.so
ld: warning: -pie being ignored. It is only used when linking a main executable
```

**Comment by rgommers** [comment]
Yeah ... this is quite annoying, but not a SciPy bug and annoying to work around. The problem is coming from conda-forge, which makes a mess of `CFLAGS`, `LDFLAGS` & co. In particular here, it inserts `-fPIE` into all compile commands and `-Wl,-pie` into `LDFLAGS`. And the latter does not work for Python extension modules.

```
% echo $LDFLAGS
-Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/rgommers/mambaforge/envs/numpy-dev/lib -L/Users/rgommers/mambaforge/envs/numpy-dev/lib

% echo $CFLAGS
-ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/rgommers/mambaforge/envs/numpy-dev/include

% echo $CXXFLAGS
-ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem /Users/rgommers/mambaforge/envs/numpy-dev/include

% echo $FFLAGS
-march=armv8.3-a -ftree-vectorize -fPIC -fno-stack-protector -O2 -pipe -isystem /Users/rgommers/mambaforge/envs/numpy-dev/include
```

Try the following more minimal set of flags, that should make these warnings go away (replacing the path to point to the right env on your machine):
```
export CFLAGS="-isystem /Users/rgommers/mambaforge/envs/numpy-dev/include"
export CXXFLAGS="-stdlib=libc++ -isystem /Users/rgommers/mambaforge/envs/numpy-dev/include"
export FFLAGS="-isystem /Users/rgommers/mambaforge/envs/numpy-dev/include"
export LDFLAGS="-isystem /Users/rgommers/mambaforge/envs/numpy-dev/include"
```

The upstream issue is https://github.com/conda-forge/conda-forge.github.io/issues/2002.

There's nothing we can do here I think, other than go help improve conda-forge. It's not worth adding this to our build docs, because there's no good way to describe how to automatically set these env vars I think, and the problem is only warnings. So we probably close this and keep this issue as documentation?

**Comment by lucascolley** [comment]
thanks for the explanation! That all makes sense.

I would probably leave the issue open to make it slightly more searchable, but close it if you prefer!

**Comment by rgommers** [comment]
This is fixed now 🎉. You should get the fix in a new env. If you want to upgrade your existing env, probably `mamba activate clang_osx-arm64` will do it (build number 8 is the fixed version).

**Comment by lucascolley** [comment]
Hmm, I tried `mamba install clang_osx-arm64=15.0.7=h54d7cd3_8` but I still see the warnings, is that not the right method? `mamba activate` doesn't seem right unless I'm missing something...

**Comment by rgommers** [comment]
You may have to deactivate/activate, because `CFLAGS` & co are set on activation.

There's lots of other packages connected to `clang`, so it's also possible you need a second package upgraded. Certainly recreating the env does it.

**Comment by lucascolley** [comment]
> You may have to deactivate/activate, because CFLAGS & co are set on activation.

That's it 👍 thanks! It should be easier to see now whether there are any warnings that aren't coming from HiGHs.

**Comment by rgommers** [comment]
Those aren't easily fixable unfortunately, since they are coming from `f2py`-generated code.
