### ISSUE TITLE
BUG: optimize.nnls: unstable on i686 (32-bit) machine

### ISSUE THREAD

**Issue by antoinebaker** [scipy/scipy#22791]
### Describe your issue.

Discovered in https://github.com/scikit-learn/scikit-learn/issues/31098 while bumping scipy version from 1.4.1 to 1.5.2 on a debian 32-bit machine. 

On the test case below, the new implementation of `nnls` (scipy 1.5.2) on the debian 32-bit machine gives badly diverging `coef`:
```python
[0.00000000e+00 3.83029964e+15 0.00000000e+00 1.15048400e+16
 1.14353389e+16 0.00000000e+00 1.33912811e+16 5.49535003e+15
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
``` 

For comparison, the old implementation (scipy 1.4.1) on the debian 32-bit machine gives sensible `coef`:
```python
[0.         0.         1.05617285 0.         0.         0.
 0.         0.23123048 0.         0.         0.         0.26128651]
``` 
On a 64-bit machine, like my mac, both scipy versions work and gives a similar `coef`.

### Reproducing Code Example

```python
import numpy as np
from scipy.optimize import nnls

rng = np.random.RandomState(42)
n_samples, n_features = 5, 12
X = rng.randn(n_samples, n_features)
X[:2, :] = 0
y = rng.randn(n_samples)
coef = nnls(X, y)[0]
print(coef)
```

### Error message

```shell
[0.00000000e+00 3.83029964e+15 0.00000000e+00 1.15048400e+16
 1.14353389e+16 0.00000000e+00 1.33912811e+16 5.49535003e+15
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
```

### SciPy/NumPy/Python version and system information

```shell
1.15.2 2.2.4 sys.version_info(major=3, minor=13, micro=2, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/include/i386-linux-gnu/openblas-pthread/
    lib directory: /usr/lib/i386-linux-gnu/openblas-pthread/
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER=1 NO_CBLAS=
      NO_LAPACK= NO_LAPACKE=1 NO_AFFINITY=1 USE_OPENMP=0 GENERIC MAX_THREADS=128
    pc file directory: /usr/lib/i386-linux-gnu/pkgconfig
    version: 0.3.29
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/include/i386-linux-gnu/openblas-pthread/
    lib directory: /usr/lib/i386-linux-gnu/openblas-pthread/
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER=1 NO_CBLAS=
      NO_LAPACK= NO_LAPACKE=1 NO_AFFINITY=1 USE_OPENMP=0 GENERIC MAX_THREADS=128
    pc file directory: /usr/lib/i386-linux-gnu/pkgconfig
    version: 0.3.29
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.13.6
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 14.2.0
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 14.2.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.12
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 14.2.0
  pythran:
    include directory: ../../../pip-build-env-5n5af3rb/overlay/lib/python3.13/site-packages/pythran
    version: 0.17.0
Machine Information:
  build:
    cpu: i686
    endian: little
    family: x86
    system: linux
  cross-compiled: false
  host:
    cpu: i686
    endian: little
    family: x86
    system: linux
Python Information:
  path: /opt/scipy1.15.2/bin/python3
  version: '3.13'
```

**Comment by ilayn** [comment]
Hi @antoinebaker we just fixed NNLS on main and I don't have any 32 bit machine that I can access. Is it possible to pull main and test it on that machine?

**Comment by lesteve** [comment]
> Hi @antoinebaker we just fixed NNLS on main and I don't have any 32 bit machine that I can access.

I am guessing you are talking about https://github.com/scipy/scipy/pull/22524 right? I saw it as well and asked @antoinebaker but according to https://github.com/scikit-learn/scikit-learn/issues/31098#issuecomment-2775653272 it seems like the issue is still in `main`. I'll let @antoinebaker confirm though.

> I don't have any 32 bit machine that I can access

FWIW you can use Docker to test 32 bit machine (this should be quite similar to the Docker image we are using in the scikit-learn CI where we discovered the issue)
```
docker run --platform linux/386 -it debian:trixie
```

**Comment by antoinebaker** [comment]
> Hi [@antoinebaker](https://github.com/antoinebaker) we just fixed NNLS on main and I don't have any 32 bit machine that I can access. Is it possible to pull main and test it on that machine?

Hi @ilayn, I confirm what @lesteve said, the problem remains on scipy `main` (after https://github.com/scipy/scipy/pull/22524) on a 32-bit machine giving `coef`
```python
[0.00000000e+00 3.83029964e+15 0.00000000e+00 1.15048400e+16
 1.14353389e+16 0.00000000e+00 1.33912811e+16 5.49535003e+15
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
```

**Comment by ilayn** [comment]
I don't have any machine around to have the docker installed but is it possible that openblas-pthread is the culprit here? There is nothing relevant in nnls code to have 64bit specifics. But the only difference is that it is making LAPACK calls

**Comment by antoinebaker** [comment]
Thanks @ilayn , I confirm that this fixes the bug as well on my debian 32-bit container.
