### ISSUE TITLE
Build failure with Cython 0.21.1

### ISSUE THREAD

**Issue by pv** [scipy/scipy#4745]
```
$ python runtests.py --python /tmp/qqq.py 
Building, see build.log...

Error compiling Cython file:
------------------------------------------------------------
...
# and object. In this file, only NULL is passed to these parameters.
cdef extern from *:
    cnp.ndarray PyArray_CheckFromAny(object, void*, int, int, int, void*)
    cnp.ndarray PyArray_FromArray(cnp.ndarray, void*, int)

from . cimport cython_blas as blas_pointers
^
------------------------------------------------------------

_decomp_update.pyx:59:0: 'scipy.linalg.' is not a valid module name
...
```
Seems to work with `Cython 0.22`.

**Comment by ewmoore** [comment]
I see that we don't specify a particular version of cython on Travis.  We should be.

**Comment by pv** [comment]
The version probably should match the requirement declared in
`tools/cythonize.py`

**Comment by insertinterestingnamehere** [comment]
I'm not seeing an easy fix other than changing the relative import to an absolute import. Would it be better to bump the version and allow relative cimports or to require that absolute cimports be used within scipy?

**Comment by rgommers** [comment]
Cython 0.22 has been out for 2 months, I don't see a problem with requiring it.

**Comment by pv** [comment]
Requiring 0.22 is the easiest solution, but if the issue is fixed just
by changing the import to be an absolute one, it could make sense to do
just that.

**Comment by rgommers** [comment]
True. Either way it's a simple fix, but not bumping the version may save people a little bit of time upgrading Cython.

**Comment by argriffing** [comment]
The earlier cython version number is also hardcoded into `/benchmarks/asv.conf.json`

**Comment by insertinterestingnamehere** [comment]
Alright, this should be fixed in https://github.com/scipy/scipy/pull/4753.
@argriffing Thanks for noticing the package version list in the benchmark suite. I wasn't aware of that.

**Comment by samuelstjean** [comment]
I tried building 0.16, 0.17dev wiht cython 0.22 and 0.23, but I still get weird error with the relative cimport such as

Processing scipy/linalg/_decomp_update.pyx.in

Error compiling Cython file:
------------------------------------------------------------
...
# and object. In this file, only NULL is passed to these parameters.
cdef extern from *:
    cnp.ndarray PyArray_CheckFromAny(object, void*, int, int, int, void*)
    cnp.ndarray PyArray_FromArray(cnp.ndarray, void*, int)

from . cimport cython_blas as blas_pointers
      ^

This is installing directly from git with pip install or trying to build locally with python setup.py build_ext -i

Anyone (still) having similar troubles? The seems to apparently fix a similar error, but maybe absolute import would be a sure fire way to fix it,

**Comment by argriffing** [comment]
> `Relative cimport is not supported yet`

I'm going to brashly suggest that the cython version you think you're using is not actually being used; that error message was removed in cython in https://github.com/cython/cython/commit/3b9f95ef995544490eef7d8687d56d20733af239.

**Comment by argriffing** [comment]
Here's an example of this kind of problem https://github.com/scipy/scipy/issues/2397, suggesting it's possible that `$ cython --version` can become de-synchronized from `$ python -c "import cython; print cython.__version__"`. Maybe the version checking in the cythonize script should be changed to explicitly check the version that would be called from subprocess instead of the version that is imported?

**Comment by samuelstjean** [comment]
Wow, you are right, I had an old global leftover installation of cython, so my local installation was working, but the compiler part was using the old one still, so I just removed everything and it works, so everything is fine after all.

**Comment by rgommers** [comment]
Good to know. Guess you found that out the hard way @argriffing :)
