### ISSUE TITLE
ValueError raised if scipy.sparse.linalg.expm recieves array larger than 200x200

### ISSUE THREAD

**Issue by TheExcalabur** [scipy/scipy#5546]
I recently ported some code from a machine running scipy 0.14 to one running 0.16 and found a breaking change.  If 'foo' is some sparse array with size greater than 200

``` python
expm(foo)
```

throws `ValueError: shapes (200,200) and (1,200) not aligned: 200 (dim 1) != 1 (dim 0)`.  

After some hunting, it looks like the breaking change is in [this commit](https://github.com/scipy/scipy/commit/7d67bd3efadeec393af853245ec52b571c75c425), where `A.T` is replaced by `A.H` on line 94 of matfuncs.py.  

If A is a matrix, this works fine.  However, expm uses the approximation routine in _onenormest_matrix_power if the matrix is 200x200 or larger, which calls `MatrixPowerOperator(A, p, structure=structure)`.  A.H then returns a `_CustomLinearOperator` instead of a `MatrixPowerOperator`, which then explodes messily.  

I see three fixes: 

Updating MatrixPowerOperator's class definition (in ...linalg.matfuncs.py) to include 

``` python
@property
def H(self):
    return MatrixPowerOperator(self._A.H, self._p) 
```

should do the trick

Alternatively, updating 

``` python
def _onenormest_matrix_power(..)
    return scipy.sparse.linalg.onenormest(aslinearoperator(A)**p,structure=structure)
```

also should work, but I'm not sure if it will break something else.  

The third fix is a bit more complicated.  For some reason, even though `MatrixPowerOperator` defines `_rmatvec`, when the `adjoint` is requested (via foo.H) on one the type gets transformed into a `_CustomLinearOperator` and doesn't inherit enough of the `MatrixPowerOperator` machinery to still cascade through the rest of expm.  That's probably an issue that should get fixed if people are going to rely on the adjoint <-> rmatvec equivalence, since it's clearly not perfect.

**Comment by larsmans** [comment]
@TheExcalabur I just tried to reproduce the issue, but I might be doing something wrong. Using current master:

```
>>> from scipy.sparse import rand
>>> from scipy.sparse.linalg import expm
>>> A = rand(300, 300, format='csr')
>>> A
<300x300 sparse matrix of type '<type 'numpy.float64'>'
	with 900 stored elements in Compressed Sparse Row format>
>>> expm(A)
<300x300 sparse matrix of type '<type 'numpy.float64'>'
	with 81257 stored elements in Compressed Sparse Row format>
>>> from scipy.sparse.linalg.matfuncs import _expm
>>> _expm(A, use_exact_onenorm=True)
<300x300 sparse matrix of type '<type 'numpy.float64'>'
	with 81257 stored elements in Compressed Sparse Row format>
>>> _expm(A, use_exact_onenorm=False)
<300x300 sparse matrix of type '<type 'numpy.float64'>'
	with 81257 stored elements in Compressed Sparse Row format>
```

Using 0.16.1 I get the same result.

**Comment by benninkrs** [comment]
The problem also occurs in scipy 0.18.0 for non-sparse, non-upper-triangular matrices 200x200 or larger:
```python
>>> from scipy import linalg
>>> import numpy as np
>>> A = np.matrix(np.fliplr(np.eye(200,200)))
>>> scipy.linalg.expm(A)
>>> linalg.expm(A)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda2\lib\site-packages\scipy\linalg\matfuncs.py", line 261, in expm
    return scipy.sparse.linalg.expm(A)
  File "C:\Anaconda2\lib\site-packages\scipy\sparse\linalg\matfuncs.py", line 582, in expm
    return _expm(A, use_exact_onenorm='auto')
  File "C:\Anaconda2\lib\site-packages\scipy\sparse\linalg\matfuncs.py", line 618, in _expm
    eta_1 = max(h.d4_loose, h.d6_loose)
  File "C:\Anaconda2\lib\site-packages\scipy\sparse\linalg\matfuncs.py", line 457, in d4_loose
    structure=self.structure)**(1/4.)
  File "C:\Anaconda2\lib\site-packages\scipy\sparse\linalg\matfuncs.py", line 301, in _onenormest_matrix_power
    MatrixPowerOperator(A, p, structure=structure))
  File "C:\Anaconda2\lib\site-packages\scipy\sparse\linalg\_onenormest.py", line 95, in onenormest
    est, v, w, nmults, nresamples = _onenormest_core(A, A.H, t, itmax)
  File "C:\Anaconda2\lib\site-packages\scipy\sparse\linalg\_onenormest.py", line 424, in _onenormest_core
    Z = np.asarray(AT_linear_operator.matmat(S))
  File "C:\Anaconda2\lib\site-packages\scipy\sparse\linalg\interface.py", line 326, in matmat
    Y = self._matmat(X)
  File "C:\Anaconda2\lib\site-packages\scipy\sparse\linalg\interface.py", line 468, in _matmat
    return super(_CustomLinearOperator, self)._matmat(X)
  File "C:\Anaconda2\lib\site-packages\scipy\sparse\linalg\interface.py", line 174, in _matmat
    return np.hstack([self.matvec(col.reshape(-1,1)) for col in X.T])
  File "C:\Anaconda2\lib\site-packages\scipy\sparse\linalg\interface.py", line 219, in matvec
    y = self._matvec(x)
  File "C:\Anaconda2\lib\site-packages\scipy\sparse\linalg\interface.py", line 471, in _matvec
    return self.__matvec_impl(x)
  File "C:\Anaconda2\lib\site-packages\scipy\sparse\linalg\interface.py", line 266, in rmatvec
    y = self._rmatvec(x)
  File "C:\Anaconda2\lib\site-packages\scipy\sparse\linalg\matfuncs.py", line 203, in _rmatvec
    x = A_T.dot(x)
ValueError: shapes (200,200) and (1,200) not aligned: 200 (dim 1) != 1 (dim 0)
```
It seems that some of the internal functions assume 2d array objects, not matrix objects.

**Comment by WarrenWeckesser** [comment]
Confirmed this is still a bug.  Here's another example.  I am using scipy 0.18.0, but it also occurs in a post-0.18.0 development version:

```
In [61]: from scipy.linalg import expm

In [62]: A = np.matrix(np.zeros((200, 200)))

In [63]: A[-1,0] = 1

In [64]: expm(A)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-64-be225a3622bd> in <module>()
----> 1 expm(A)

/Users/warren/miniconda3/lib/python3.5/site-packages/scipy/linalg/matfuncs.py in expm(A, q)
    259     # Input checking and conversion is provided by sparse.linalg.expm().
    260     import scipy.sparse.linalg
--> 261     return scipy.sparse.linalg.expm(A)
    262 
    263 

/Users/warren/miniconda3/lib/python3.5/site-packages/scipy/sparse/linalg/matfuncs.py in expm(A)
    580 
    581     """
--> 582     return _expm(A, use_exact_onenorm='auto')
    583 
    584 

/Users/warren/miniconda3/lib/python3.5/site-packages/scipy/sparse/linalg/matfuncs.py in _expm(A, use_exact_onenorm)
    616 
    617     # Try Pade order 3.
--> 618     eta_1 = max(h.d4_loose, h.d6_loose)
    619     if eta_1 < 1.495585217958292e-002 and _ell(h.A, 3) == 0:
    620         U, V = h.pade3()

/Users/warren/miniconda3/lib/python3.5/site-packages/scipy/sparse/linalg/matfuncs.py in d4_loose(self)
    455             if self._d4_approx is None:
    456                 self._d4_approx = _onenormest_matrix_power(self.A2, 2,
--> 457                         structure=self.structure)**(1/4.)
    458             return self._d4_approx
    459 

/Users/warren/miniconda3/lib/python3.5/site-packages/scipy/sparse/linalg/matfuncs.py in _onenormest_matrix_power(A, p, t, itmax, compute_v, compute_w, structure)
    299     """
    300     return scipy.sparse.linalg.onenormest(
--> 301             MatrixPowerOperator(A, p, structure=structure))
    302 
    303 

/Users/warren/miniconda3/lib/python3.5/site-packages/scipy/sparse/linalg/_onenormest.py in onenormest(A, t, itmax, compute_v, compute_w)
     93         est = col_abs_sums[argmax_j]
     94     else:
---> 95         est, v, w, nmults, nresamples = _onenormest_core(A, A.H, t, itmax)
     96 
     97     # Report the norm estimate along with some certificates of the estimate.

/Users/warren/miniconda3/lib/python3.5/site-packages/scipy/sparse/linalg/_onenormest.py in _onenormest_core(A, AT, t, itmax)
    422         del S_old
    423         # (3)
--> 424         Z = np.asarray(AT_linear_operator.matmat(S))
    425         nmults += 1
    426         h = _max_abs_axis1(Z)

/Users/warren/miniconda3/lib/python3.5/site-packages/scipy/sparse/linalg/interface.py in matmat(self, X)
    324                              % (self.shape, X.shape))
    325 
--> 326         Y = self._matmat(X)
    327 
    328         if isinstance(Y, np.matrix):

/Users/warren/miniconda3/lib/python3.5/site-packages/scipy/sparse/linalg/interface.py in _matmat(self, X)
    466             return self.__matmat_impl(X)
    467         else:
--> 468             return super(_CustomLinearOperator, self)._matmat(X)
    469 
    470     def _matvec(self, x):

/Users/warren/miniconda3/lib/python3.5/site-packages/scipy/sparse/linalg/interface.py in _matmat(self, X)
    172         """
    173 
--> 174         return np.hstack([self.matvec(col.reshape(-1,1)) for col in X.T])
    175 
    176     def _matvec(self, x):

/Users/warren/miniconda3/lib/python3.5/site-packages/scipy/sparse/linalg/interface.py in <listcomp>(.0)
    172         """
    173 
--> 174         return np.hstack([self.matvec(col.reshape(-1,1)) for col in X.T])
    175 
    176     def _matvec(self, x):

/Users/warren/miniconda3/lib/python3.5/site-packages/scipy/sparse/linalg/interface.py in matvec(self, x)
    217             raise ValueError('dimension mismatch')
    218 
--> 219         y = self._matvec(x)
    220 
    221         if isinstance(x, np.matrix):

/Users/warren/miniconda3/lib/python3.5/site-packages/scipy/sparse/linalg/interface.py in _matvec(self, x)
    469 
    470     def _matvec(self, x):
--> 471         return self.__matvec_impl(x)
    472 
    473     def _rmatvec(self, x):

/Users/warren/miniconda3/lib/python3.5/site-packages/scipy/sparse/linalg/interface.py in rmatvec(self, x)
    264             raise ValueError('dimension mismatch')
    265 
--> 266         y = self._rmatvec(x)
    267 
    268         if isinstance(x, np.matrix):

/Users/warren/miniconda3/lib/python3.5/site-packages/scipy/sparse/linalg/matfuncs.py in _rmatvec(self, x)
    201         x = x.ravel()
    202         for i in range(self._p):
--> 203             x = A_T.dot(x)
    204         return x
    205 

ValueError: shapes (200,200) and (1,200) not aligned: 200 (dim 1) != 1 (dim 0)
```

**Comment by CarloNicolini** [comment]
The bug still open after almost 1 year. Fortunately I just need eigenvalues so calling expm is not necessary as exponentiating eigenvalues of my matrix is enough.
But this problem is big in my opinion.

**Comment by person142** [comment]
A fix was begun in https://github.com/scipy/scipy/pull/5591 but the effort stalled. @CarloNicolini would you like to take it over?

**Comment by YassineAbdelouadoud** [comment]
This has not yet been fixed in scipy 1.0. Moreover, expm2, that I am using as a fallback when expm fails, has been removed from scipy 1.0. As a consequence, I am stuck with scipy 0.19.0 for the time being. Are there any plans to fix this bug or, at least, to bring back expm2 until this bug is fixed ?

**Comment by pv** [comment]
Just use expm(np.asarray(A))

**Comment by lobpcg** [comment]
The bug is still here: 
```
A = np.matrix(np.zeros((200, 200)))
A[-1, 0] = 1
# this passes
B = expm(np.asarray(A))
# This fails
B = expm(A)
```

The fix is apparently is as trivial as just turning the matrix argument into an array in some of the functions.
