### ISSUE TITLE
scipy.stats.spearmanr return values outside range -1 to 1

### ISSUE THREAD

**Issue by WaqAli** [scipy/scipy#6061]
While calculating the correlation for two vectors (with some missing values), scipy.stats.spearman returns values greater than 1:

In [12]: ss.spearmanr(eur_af_transformed, data['standardized_se'],nan_policy='omit')[0]
Out[12]: 2.5865646154828417

In [2]: scipy.version.version
Out[2]: '0.17.0'

scipy.stats.mstats.spearmanr also returns invalid values:

In [17]: ss.mstats.spearmanr(eur_af_transformed, data['standardized_se'])
Out[17]: SpearmanrResult(correlation=-2.8721254146781465, pvalue=0.0)

**Comment by ev-br** [comment]
Can you please add a reproducible example

**Comment by kbrose** [comment]
@ev-br 

```python
>>> np.random.seed(2017)
>>> x = np.random.rand(3500)
>>> y = np.random.rand(3500)
>>> x[5] = np.nan
>>> r, p = scipy.stats.spearmanr(x, y, nan_policy='omit')
>>> r
374.21526668172135
>>> p
0.0
>>> scipy.__version__
'0.18.1'
>>> np.__version__
'1.11.3'
```

**Comment by ev-br** [comment]
Thanks @WaqAli

This has been fixed:

```
In [12]: r, p = spearmanr(x, y, nan_policy='omit')

In [13]: r
Out[13]: 0.029322382934487745

In [14]: p
Out[14]: 
masked_array(data = 0.0828753538887,
             mask = False,
       fill_value = 1e+20)

In [15]: scipy.__version__
Out[15]: '0.19.0rc1'
```

Having `pvalue` a masked array is probably an artefact, which deserves a separate ticket.
Closing this one as resolved.

**Comment by kbrose** [comment]
Thanks for the quick reply. Do you mind telling me what OS you are using? I've seen discrepancies where the bug only occurs on Windows machines. Likely related to this: http://stackoverflow.com/questions/36278590/numpy-array-dtype-is-coming-as-int32-by-default-in-a-windows-10-64-bit-machine

**Comment by WarrenWeckesser** [comment]
I'm not convinced this isn't still an issue.  I don't have a Windows installation to test this, but here's what I think is happening in `spearmanr` when using Windows (where the default `int` dtype is 32 bits).

The first few lines of `spearmanr` are:

    (x, y, n) = _chk_size(x, y)
    (x, y) = (x.ravel(), y.ravel())

    m = ma.mask_or(ma.getmask(x), ma.getmask(y))
    n -= m.sum()

The value `n` returned from `_chk_size` (3500 in the example) should be a Python integer, which is effectively arbitrary precision in Python 3, so that is not the problem.  But then we do `n -= m.sum()`.  Python integers are immutable, so this is not really an in-place operation.  That is, it really does `n = n - m.sum()`.  `m.sum()` return a *numpy* integer, and on Windows, that will be a 32 bit integer.  So the new value of `n` is a numpy integer.  Then, when this line is reached,

    denom = n*(n**2 - 1)/6.

that integer overflows.

**Comment by WarrenWeckesser** [comment]
A fix could be as simple as changing `n -= m.sum()` to

    n -= int(m.sum())

so `n` remains a Python integer and won't overflow when `n*(n**2 - 1)` is computed.

**Comment by kbrose** [comment]
@WarrenWeckesser Easier solution than what I was thinking (I was thinking about how to refactor `denom` out so you wouldn't have to cube anything in an intermediate value).

Do you all have Windows CI tests?

**Comment by ev-br** [comment]
OK, I might try to set up an Anaconda install on a Windows machine to test this. No ETA though, so if someone beats me to it, great. It should be easy enough, as https://github.com/scipy/scipy/blob/master/scipy/stats/mstats_basic.py#L416 is pure python, so one can just toss in a breakpoint.

@WaqAli Unfortunately, no, we don't have any Windows CI at the moment. Setting one up would be great (hint, hint :-)).

**Comment by kbrose** [comment]
No worries about the CI. I know setting one up for windows is a non-trivial task. I didn't realize that the definition is in pure python (I actually couldn't track where the exact definition of the function was, I'd found the function you linked to but it has a different API than shown [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.spearmanr.html)) so as you say full build probably not needed.

Changing the offending line to `n -= int(m.sum())` made it work for me. If that's all there is to it I'll probably submit a short PR later today (unless someone else here wants to do it).

Also just a heads up I think you're "@"-ing the OP, which I am not :)

**Comment by ev-br** [comment]
Oh, sorry Kevin, I should not be pinging strangers on the internet at 2am local time :-). 

Please do submit a PR, ideally with a test. Now could be great time for windows bug fixes as we're lucky to have the CI by Christoph Gohlke.

**Comment by WarrenWeckesser** [comment]
@kbrose wrote:

> I actually couldn't track where the exact definition of the function was, I'd found the function you linked to but it has a different API than shown here

Ah, right.  The main definition, with signature

    def spearmanr(a, b=None, axis=0, nan_policy='propagate'):

is in `scipy/stats/stats.py`.  In some cases (including your example), that function calls the function with signature

    def spearmanr(x, y, use_ties=True):

that is defined in `scipy/stats/mstats_basic.py`.
