### ISSUE TITLE
Nonzero method of CSC matrix does not account of zeroed-out data.

### ISSUE THREAD

**Issue by jni** [scipy/scipy#6065]
It seems that the `nonzero` method in CSC matrices is unaware of zeroed out data, in contrast to the identical method in CSR matrices:

```python
>>> x = sparse.csr_matrix(np.array([[0, 1, 0, 0], [0, 1, 2, 0]]))
>>> x[1, 2] = 0
>>> x.data
array([1, 1, 0], dtype=int64)
>>> x.toarray()
array([[0, 1, 0, 0],
       [0, 1, 0, 0]], dtype=int64)
>>> y = x.T
>>> type(y)
scipy.sparse.csc.csc_matrix
>>> x.nonzero()
(array([0, 1], dtype=int32), array([1, 1], dtype=int32))
>>> y.nonzero()
(array([1, 1, 2], dtype=int32), array([0, 1, 1], dtype=int32))
```

Python 3.5, SciPy 0.17.

**Comment by perimosocordiae** [comment]
This has been fixed between your version and the latest master:

```
In [1]: import scipy.sparse as ss

In [2]: x = ss.csr_matrix([[0,1,0,0],[0,1,2,0]])

In [3]: x[1,2] = 0

In [4]: x.data
Out[4]: array([1, 1, 0])

In [5]: x.toarray()
Out[5]:
array([[0, 1, 0, 0],
       [0, 1, 0, 0]])

In [6]: y = x.T

In [7]: y
Out[7]:
<4x2 sparse matrix of type '<type 'numpy.int64'>'
        with 3 stored elements in Compressed Sparse Column format>

In [8]: x.nonzero()
Out[8]: (array([0, 1], dtype=int32), array([1, 1], dtype=int32))

In [9]: y.nonzero()
Out[9]: (array([1, 1], dtype=int32), array([0, 1], dtype=int32))
```

**Comment by perimosocordiae** [comment]
It looks like the commit that fixed this may have been f1ce87f99e143246d55b9f45b704563f5f5ac2a7, which should be included in version 0.17, so I'm not sure why you're hitting this bug. If you can, try updating to the current master and trying again?

**Comment by jni** [comment]
Well a brand new conda env with just "python=3.5 scipy" as requirements still doesn't work on my end. Unfortunately I'm having issues compiling inside an env on OSX:

```python
gcc -bundle -undefined dynamic_lookup -L/Users/jni/conda/envs/scipy/lib -arch x86_64 build/temp.macosx-10.5-x86_64-3.5/scipy/cluster/_vq.o -L/Users/jni/conda/envs/scipy/lib -L/Users/jni/conda/envs/scipy/lib -Lbuild/temp.macosx-10.5-x86_64-3.5 -lmkl_lapack95_lp64 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -o build/lib.macosx-10.5-x86_64-3.5/scipy/cluster/_vq.cpython-35m-darwin.so
ld: library not found for -lmkl_lapack95_lp64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ld: library not found for -lmkl_lapack95_lp64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: Command "gcc -bundle -undefined dynamic_lookup -L/Users/jni/conda/envs/scipy/lib -arch x86_64 build/temp.macosx-10.5-x86_64-3.5/scipy/cluster/_vq.o -L/Users/jni/conda/envs/scipy/lib -L/Users/jni/conda/envs/scipy/lib -Lbuild/temp.macosx-10.5-x86_64-3.5 -lmkl_lapack95_lp64 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -o build/lib.macosx-10.5-x86_64-3.5/scipy/cluster/_vq.cpython-35m-darwin.so" failed with exit status 1
```

**Comment by pv** [comment]
gh-5394 is only in master, not in 0.17.0.

**Comment by perimosocordiae** [comment]
Ah, I was mistaken, then. Closing.
