### ISSUE TITLE
slsqp catches all exceptions, masking objective function evaluation failures

### ISSUE THREAD

**Issue by jllanfranchi** [scipy/scipy#7232]
This code in scipy/optimize/slsqp.py is problematic, and also fails to abide by basic Python standards for exception handling.
https://github.com/scipy/scipy/blob/master/scipy/optimize/slsqp.py#L367-L370
```python
            try:
                fx = float(np.asarray(func(x)))
            except:
                raise ValueError("Objective function must return a scalar")
```

The function evaluation itself should occur outside the try/except block, while the type check is fine to do within the try/except. But a specific exception(s) should be handled, too, rather than the catch-all as it's constructed. As it stands, e.g. an error in evaluating `func` on `x` always displays the unhelpful (if not misleading) error message `"Objective function must return a scalar"`.

E.g. a fix for this might look like:
```python
            fx = func(x)
            try:
                fx = float(np.asarray(fx))
            except TypeError:
                raise ValueError("Objective function must return a scalar")
```
I might have missed a case where another exception type should be caught, but `TypeError` is what `float` raises when I try produce the kind of value that this code appears to be trying to catch.

**Comment by person142** [comment]
Fixed in https://github.com/scipy/scipy/pull/7233.

**Comment by snassimr** [comment]
Does scipy 0.19.0 solve the issue for Python3.5.2 ? I am still getting the error

**Comment by rgommers** [comment]
No, gh-7233 is not part of 0.19.0, it will be in 1.0
