### ISSUE TITLE
Documentation of Bessel Functions

### ISSUE THREAD

**Issue by Noxbru** [scipy/scipy#7741]
Hi,

I think there's some little mistakes in the documentation of Bessel Functions:

1. [Jn](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.jn.html#scipy.special.jn) and [Jv](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.jv.html#scipy.special.jv) seem to be the same, although probably Jn should only receive integer orders and real arguments, just like Yn and Yv do.

2. In the notes for both functions, it is said that they are calculated using the connection to the Modified Bessel Function I. I'm afraid that the formula has a typo:

$\J_v(z) = exp(n \pi i / 2) I_v(-i z)$

The 'n' in the exponential should be a 'v'.

Thanks in advance.

**Comment by person142** [comment]
Relevant discussions are here:

https://github.com/scipy/scipy/issues/2564

and here:

https://github.com/scipy/scipy/pull/3684

In short, these issues were fixed but appear to have crept back in.

**Comment by person142** [comment]
Oh, also the decision to make `Jn` and `Jv` aliases was in https://github.com/scipy/scipy/issues/925.

**Comment by Noxbru** [comment]
@person142 oh, thanks for the references. I didn't know that in that case they were indeed the same function.

Still, the second tiny issue remains. (Although it's just a minor typo)

**Comment by person142** [comment]
> Still, the second tiny issue remains. (Although it's just a minor typo)

Yes; should be a quick fix if you'd like to make a PR?

**Comment by Noxbru** [comment]
@person142 Done I think. It took me longer to find where I had to change the docs than the change itself.

**Comment by person142** [comment]
> It took me longer to find where I had to change the docs than the change itself.

Yes... that part is tricky. Opened https://github.com/scipy/scipy/issues/7745 to work on getting the process better documented.

**Comment by person142** [comment]
Leaving this issue open since (2) was addressed in https://github.com/scipy/scipy/pull/7743, but for (1) it seems that we should remove `jn` from the refguide (again).
