### ISSUE TITLE
interp2d doesn't extrapolate as per documentation, instead uses nearest-neighbor

### ISSUE THREAD

**Issue by ddasilva** [scipy/scipy#8099]
The documentation for interp2d [0] says that when fill_value is left as default, values outside the domain are extrapolated. It seems to just copy the nearest neighbor. 

[0] https://docs.scipy.org/doc/scipy-0.19.1/reference/generated/scipy.interpolate.interp2d.html

### Reproducing code example:
https://gist.github.com/ddasilva/1a020ff09e6fef688dd1c9acf5659f50

### Error message:
No error message occurs.

### Scipy/Numpy/Python version information:
```
('0.19.1', '1.13.1', sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0))
In [60]:
```

**Comment by WarrenWeckesser** [comment]
This might just be a problem with the documentation. The docstring says that values for points outside the interpolation domain are extrapolated, but it doesn't specify the extrapolation method.  Since "nearest neighbor" is a form of extrapolation, one could say that the docstring is technically correct, but that isn't very helpful.  The docstring should be updated to state explicitly the extrapolation method.

**Comment by ddasilva** [comment]
Thx Warren. This was especially confusing because my expectation was based off the capabilities of `interp1d` .

Looking at the source, it appears nearest-neighbor is default behavior `fitpack.bisplev`; the author of `interp2d` on the SciPy side doesn't handle the case where `fill_value=None` and `bounds_error=False`.  

https://github.com/scipy/scipy/blob/master/scipy/interpolate/interpolate.py#L285

In the mean time, what in SciPy can I use for taking data and doing both 2D linear interpolation and extrapolation?

**Comment by ddasilva** [comment]
I fixed my problem by extrapolating the missing points manually. Closing the ticket; reopen if need be.

**Comment by pv** [comment]
Please reopen --- the bug is still there, regardless of whether there is 
a work-around that can be done in a different way.

**Comment by ddasilva** [comment]
Reopening at request of @pv. So is this just a doc bug?

**Comment by craigim** [comment]
Just spent over an hour trying to figure out why my interpolated matrix was not properly extrapolating at the edges. Personally, if I specify linear interpolation and leave fill_value as default, I expect the extrapolation method to be the same as the interpolation method, not an undocumented different method.

**Comment by jmmanley** [comment]
My PR #10506 addresses the documentation issue, but it would still be nice to offer better extrapolation like in `interp1d`. I will take a look into this in my spare time.. For now, I found this quick fix from @pig2015 that inherits `interp2d` for extrapolation: https://github.com/pig2015/mathpy/blob/master/polation/globalspline.py

**Comment by ev-br** [comment]
Given that interp2d is now deprecated in scipy 1.10 and will be removed in a future scipy version, it will not get fixed.

A feature request for adding extrapolation to RectBivariateSpline et al is tracked in https://github.com/scipy/scipy/issues/3361, and there is a pointer on a possible implementation. 
An alternative is of course to use RegularGridInterpolator which allows extrapolation.

I'm going to close the issue, but feel free to continue the discussion. Thanks @ddasilva , all.
