### ISSUE TITLE
scipy.optimize.minimize, method = 'trust-constr': jac and hess are not truly optional

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#8867]
The documentation states that arguments `jac` and `hess` are optional for `scipy.optimize.minimize`, but they are not optional when using `method = 'trust-constr'`. 

### Reproducing code example:
```
import scipy

def fun(x):
    return (x-1)**2

bounds = [(-2, 2)]
res = scipy.optimize.minimize(fun, x0 = [-1.5], bounds=bounds, method = 'trust-constr')
# res = scipy.optimize.minimize(fun, x0 = [-1.5], bounds=bounds, jac='2-point', method = 'trust-constr')
```

### Error message:
```
Traceback (most recent call last):

  File "<ipython-input-12-34d1ad1b642b>", line 1, in <module>
    runfile('C:/Users/matth/Desktop/untitled0.py', wdir='C:/Users/matth/Desktop')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/matth/Desktop/untitled0.py", line 14, in <module>
    res = scipy.optimize.minimize(fun, x0 = [-1.5], bounds=bounds, method = 'trust-constr')

  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\_minimize.py", line 543, in minimize
    raise ValueError("Unsupported jac definition.")

ValueError: Unsupported jac definition.
```

Or, with the first commented-out line I get:
`ValueError: `hess` must be either callable,HessianUpdateStrategy or one of ('2-point', '3-point', 'cs').`

### Scipy/Numpy/Python version information:
```
1.1.0 1.14.0 sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)
```

**Comment by antonior92** [comment]
Thank you for reporting it Matt. I will see if I can reproduce the error.

**Comment by antonior92** [comment]
Ok, I fixed this problem in PR #8883

**Comment by DjoleMNE** [comment]
Hey @antonior92. I am still getting the same error which @mdhaber was receiving. I.e. ``ValueError:hess must be either callable,HessianUpdateStrategy or one of ('2-point', '3-point', 'cs')``

I was running the same example:
``
import scipy
``
``
def fun(x):
    return (x-1)**2 ``

``
bounds = [(-2, 2)]
``
``
res = scipy.optimize.minimize(fun, x0 = [-1.5], bounds=bounds, jac='2-point', method = 'trust-constr') 
``

**Comment by DjoleMNE** [comment]
Hey @antonior92. I am still getting the same error which @mdhaber was receiving. I.e. ``ValueError:hess must be either callable,HessianUpdateStrategy or one of ('2-point', '3-point', 'cs')``

I was running the same example:
``
import scipy
``
``
def fun(x):
    return (x-1)**2 ``

``
bounds = [(-2, 2)]
``
``
res = scipy.optimize.minimize(fun, x0 = [-1.5], bounds=bounds, jac='2-point', method = 'trust-constr') 
``

**Comment by antonior92** [comment]
@DjoleMNE, what scipy version are you using? Because I think this will be available only on release 1.2

If you compile scipy master branch from source you should get this fix.

**Comment by DjoleMNE** [comment]
thanks for reply @antonior92. I am using 1.1 version. I will try with 1.2 now

**Comment by DjoleMNE** [comment]
It is working now. Thanks a lot @antonior92 !
